'use client';

export type ClientPreferences={language:'es'|'en';graphicsPreset:'auto'|'low'|'medium'|'high';musicVolume:number;effectsVolume:number;muted:boolean;reducedMotion:boolean};
const defaults:ClientPreferences={language:'es',graphicsPreset:'auto',musicVolume:.35,effectsVolume:.55,muted:false,reducedMotion:false};
let ctx:AudioContext|null=null;let ambient:OscillatorNode[]=[];let ambientGain:GainNode|null=null;let installed=false;
export function loadPreferences():ClientPreferences{if(typeof window==='undefined')return defaults;try{return{...defaults,...JSON.parse(localStorage.getItem('nr_preferences')??'{}')}}catch{return defaults}}
export function savePreferences(p:ClientPreferences){localStorage.setItem('nr_preferences',JSON.stringify(p));applyPreferences(p);}
export function applyPreferences(p=loadPreferences()){if(typeof document==='undefined')return;document.documentElement.lang=p.language;document.documentElement.dataset.graphics=p.graphicsPreset;document.documentElement.dataset.reducedMotion=p.reducedMotion?'true':'false';if(ambientGain)ambientGain.gain.value=p.muted?0:Math.max(0,Math.min(.035,p.musicVolume*.035));}
function audio(){if(typeof window==='undefined')return null;ctx??=new AudioContext();if(ctx.state==='suspended')void ctx.resume();return ctx;}
export function playUiTone(kind:'tap'|'success'|'error'='tap'){const p=loadPreferences();if(p.muted||p.effectsVolume<=0)return;const a=audio();if(!a)return;const osc=a.createOscillator(),gain=a.createGain();osc.type=kind==='success'?'sine':kind==='error'?'sawtooth':'triangle';osc.frequency.value=kind==='success'?620:kind==='error'?150:360;const now=a.currentTime;gain.gain.setValueAtTime(Math.min(.05,p.effectsVolume*.045),now);gain.gain.exponentialRampToValueAtTime(.0001,now+.045);osc.connect(gain).connect(a.destination);osc.start(now);osc.stop(now+.05);}
export function setAmbientMusic(enabled:boolean){const p=loadPreferences();const a=audio();if(!a)return;if(!enabled||p.muted||p.musicVolume<=0){for(const o of ambient)try{o.stop()}catch{}ambient=[];ambientGain?.disconnect();ambientGain=null;return;}if(ambient.length)return;ambientGain=a.createGain();ambientGain.gain.value=Math.max(0,Math.min(.035,p.musicVolume*.035));ambientGain.connect(a.destination);for(const f of [55,82.41]){const o=a.createOscillator();o.type='sine';o.frequency.value=f;o.connect(ambientGain);o.start();ambient.push(o);}}
export function installButtonSounds(){if(installed||typeof document==='undefined')return;installed=true;applyPreferences();document.addEventListener('click',e=>{const target=e.target as HTMLElement|null;if(target?.closest('button:not(:disabled)'))playUiTone('tap')},{passive:true});}
