'use client';

import { useEffect, useState } from 'react';
import { Activity, Ban, BarChart3, CalendarDays, Coins, RefreshCw, Search, ShieldCheck, Swords, UserRoundCog, Users } from 'lucide-react';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
const h=()=>({authorization:`Bearer ${sessionStorage.getItem('nr_session')??''}`,'content-type':'application/json'});
const tabs=[['overview','Resumen',Activity],['analytics','Analítica',BarChart3],['events','Eventos',CalendarDays],['economy','Economía',Coins],['clans','Clanes',Users],['players','Jugadores',UserRoundCog]] as const;
export function AdminPanel(){
 const[ready,setReady]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[overview,setOverview]=useState<any>(null),[data,setData]=useState<any>(null),[players,setPlayers]=useState<any[]>([]),[q,setQ]=useState(''),[busy,setBusy]=useState(false);
 async function authenticate(){const existing=sessionStorage.getItem('nr_session');if(existing){setReady(true);return;}const initData=window.Telegram?.WebApp?.initData;if(!initData){setError('Abre el panel desde Telegram.');return;}const r=await fetch(`${apiUrl}/v1/auth/telegram`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({initData})});const j=await r.json();if(!r.ok){setError('Autenticación fallida.');return;}sessionStorage.setItem('nr_session',j.token);setReady(true);}
 async function get(path:string){const r=await fetch(`${apiUrl}${path}`,{headers:h()});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'FORBIDDEN');return j;}
 useEffect(()=>{void authenticate()},[]);
 useEffect(()=>{if(!ready)return;get('/v1/admin/overview').then(j=>setOverview(j.stats)).catch(()=>setError('Tu Telegram ID no está autorizado como administrador.'));},[ready]);
 useEffect(()=>{if(!ready||!overview||tab==='overview'||tab==='players')return;setData(null);const path=tab==='analytics'?'/v1/admin/analytics':tab==='events'?'/v1/admin/events':tab==='economy'?'/v1/admin/economy':'/v1/admin/clans';get(path).then(setData).catch(e=>setError(String(e.message)));},[tab,ready,overview]);
 async function search(){const j=await get(`/v1/admin/players?q=${encodeURIComponent(q)}`);setPlayers(j.players??[]);}
 async function ban(p:any){await fetch(`${apiUrl}/v1/admin/players/${p.id}/ban`,{method:'POST',headers:h(),body:JSON.stringify({banned:!p.is_banned,reason:'admin_panel'})});await search();}
 async function gold(p:any){const raw=window.prompt('Cantidad de oro a sumar (negativo para retirar):','100');if(!raw)return;const amount=Number(raw);if(!Number.isFinite(amount))return;await fetch(`${apiUrl}/v1/admin/players/${p.id}/grant`,{method:'POST',headers:h(),body:JSON.stringify({currency:'gold',amount,reason:'admin_panel'})});}
 async function launch(eventId:string){const raw=window.prompt('Duración del evento en horas:','24');if(!raw)return;const durationHours=Math.max(1,Math.min(336,Number(raw)));if(!Number.isFinite(durationHours))return;setBusy(true);try{const r=await fetch(`${apiUrl}/v1/admin/events/${eventId}/launch`,{method:'POST',headers:h(),body:JSON.stringify({durationHours,reason:'admin_panel'})});if(!r.ok)throw new Error('No se pudo iniciar el evento');setData(await get('/v1/admin/events'));}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function finish(instanceId:string){setBusy(true);try{await fetch(`${apiUrl}/v1/admin/events/${instanceId}/finish`,{method:'POST',headers:h(),body:'{}'});setData(await get('/v1/admin/events'));}finally{setBusy(false)}}
 if(error)return <main className="admin-shell"><ShieldCheck/><h1>Panel administrativo</h1><p>{error}</p></main>;
 if(!ready||!overview)return <main className="admin-shell"><ShieldCheck/><h1>Panel administrativo</h1><p>Validando acceso…</p></main>;
 return <main className="admin-shell"><header><div><ShieldCheck/><span><small>PRIVADO · AUDITADO</small><h1>Nexus Control</h1></span></div><button className="admin-refresh" onClick={()=>location.reload()}><RefreshCw/></button></header><nav className="admin-tabs">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/><span>{label}</span></button>)}</nav>
 {tab==='overview'&&<><section className="admin-kpis">{Object.entries(overview).map(([k,v])=><article key={k}><b>{String(v)}</b><span>{k.replaceAll('_',' ')}</span></article>)}</section><section className="admin-card"><h2><ShieldCheck/> Estado operativo</h2><p className="admin-copy">LiveOps, economía, clanes y acciones administrativas están separados del cliente y las escrituras sensibles quedan auditadas.</p></section></>}
 {tab==='analytics'&&data&&<><section className="admin-kpis">{Object.entries(data.summary??{}).map(([k,v])=><article key={k}><b>{String(v)}</b><span>{k.replaceAll('_',' ')}</span></article>)}</section><section className="admin-card"><h2><BarChart3/> Retención</h2><div className="admin-retention"><span>Cohorte <b>{data.retention?.cohort??0}</b></span><span>D1 <b>{data.retention?.d1??0}</b></span><span>D3 <b>{data.retention?.d3??0}</b></span><span>D7 <b>{data.retention?.d7??0}</b></span></div></section><section className="admin-card"><h2>Uso de pantallas</h2><div className="admin-table">{(data.screens??[]).map((r:any)=><article key={r.screen}><b>{r.screen||'desconocida'}</b><span>{r.views} vistas · {r.players} jugadores</span></article>)}</div></section></>}
 {tab==='events'&&data&&<><section className="admin-card"><h2><CalendarDays/> Catálogo LiveOps</h2><div className="admin-table">{(data.definitions??[]).map((e:any)=><article key={e.id}><div><b>{e.name_es}</b><span>{e.event_type} · {e.enabled?'activo':'deshabilitado'}</span></div><button disabled={busy||!e.enabled} onClick={()=>launch(e.id)}>LANZAR</button></article>)}</div></section><section className="admin-card"><h2>Instancias recientes</h2><div className="admin-table">{(data.instances??[]).map((e:any)=><article key={e.id}><div><b>{e.name_es}</b><span>{e.status} · {e.contributors} participantes · {e.contribution} puntos</span></div>{e.status==='active'&&<button disabled={busy} onClick={()=>finish(e.id)}>FINALIZAR</button>}</article>)}</div></section></>}
 {tab==='economy'&&data&&<><section className="admin-kpis"><article><b>{data.earn?.total??0}</b><span>Earn interno total</span></article><article><b>{data.market?.active??0}</b><span>Mercado activo</span></article><article><b>{data.market?.sold_volume??0}</b><span>Volumen vendido</span></article></section><section className="admin-card"><h2><Coins/> Recursos en circulación</h2><div className="admin-table">{(data.resources??[]).map((r:any)=><article key={r.resource_code}><b>{r.resource_code}</b><span>Total {r.total} · {r.holders} jugadores · máximo {r.max_balance}</span></article>)}</div></section><section className="admin-card"><h2>Flujo últimas 24 h</h2><div className="admin-table">{(data.ledger??[]).map((r:any,i:number)=><article key={`${r.currency}-${r.reason}-${i}`}><b>{r.currency} · {r.reason}</b><span>{r.operations} operaciones · neto {r.net_delta} · volumen {r.volume}</span></article>)}</div></section></>}
 {tab==='clans'&&data&&<><section className="admin-card"><h2><Users/> Clanes</h2><div className="admin-table">{(data.clans??[]).map((c:any)=><article key={c.id}><b>[{c.tag}] {c.name}</b><span>Nv. {c.level} · {c.members} miembros · EXP {c.experience} · tesorería {c.treasury_total}</span></article>)}</div></section><section className="admin-card"><h2><Swords/> Guerras</h2><div className="admin-table">{(data.wars??[]).map((w:any)=><article key={w.id}><b>{w.clan_a_name} {w.score_a} : {w.score_b} {w.clan_b_name}</b><span>{w.status}</span></article>)}</div></section></>}
 {tab==='players'&&<section className="admin-card"><h2><UserRoundCog/> Jugadores</h2><div className="admin-search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nombre, usuario o Telegram ID"/><button onClick={search}><Search/>Buscar</button></div><div className="admin-players">{players.map(p=><article key={p.id}><div><b>{p.character_name??p.display_name}</b><span>@{p.username??'sin_usuario'} · Nv. {p.level??'-'} · Poder {p.power??0}</span></div><button onClick={()=>gold(p)}><Coins/>Oro</button><button className={p.is_banned?'unban':'danger'} onClick={()=>ban(p)}><Ban/>{p.is_banned?'Activar':'Suspender'}</button></article>)}</div></section>}
 {!data&&['analytics','events','economy','clans'].includes(tab)&&<section className="admin-card"><p>Cargando datos administrativos…</p></section>}
 <p className="admin-note">Todas las modificaciones de recursos, suspensiones, eventos y configuración quedan registradas en el audit log del servidor.</p></main>;
}
