'use client';

import { useEffect, useState } from 'react';
import { Archive, Castle, Clock3, FlaskConical, Flower2, Hammer, Landmark, LoaderCircle, Mountain, Pickaxe, Shield, ShoppingBasket, Sparkles, Swords, TowerControl, Trees, Waves, Warehouse, X } from 'lucide-react';
import type { Snapshot } from './GameHome';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
const auth=()=>({authorization:`Bearer ${sessionStorage.getItem('nr_session')??''}`});
const action=()=>({...auth(),'idempotency-key':crypto.randomUUID()});
const num=(v:unknown)=>Number(v??0);
const labels:Record<string,{name:string;Icon:any,zone:string}>={fortress:{name:'Fortaleza',Icon:Castle,zone:'citadel'},forge:{name:'Herrería',Icon:Hammer,zone:'craft'},laboratory:{name:'Laboratorio',Icon:FlaskConical,zone:'arcane'},garden:{name:'Jardín',Icon:Flower2,zone:'nature'},mine:{name:'Mina',Icon:Pickaxe,zone:'resource'},pond:{name:'Estanque',Icon:Waves,zone:'nature'},warehouse:{name:'Almacén',Icon:Warehouse,zone:'utility'},market:{name:'Mercado',Icon:ShoppingBasket,zone:'utility'},altar:{name:'Altar',Icon:Sparkles,zone:'arcane'},barracks:{name:'Cuartel',Icon:Swords,zone:'military'},'arcane-tower':{name:'Torre Arcana',Icon:TowerControl,zone:'arcane'},workshop:{name:'Taller',Icon:Archive,zone:'craft'},portal:{name:'Portal',Icon:Landmark,zone:'arcane'},'hall-of-heroes':{name:'Salón de Héroes',Icon:Shield,zone:'citadel'}};
const errors:Record<string,string>={INSUFFICIENT_GOLD:'No tienes suficiente oro.',INSUFFICIENT_RESOURCES:'Te faltan materiales.',ALREADY_UPGRADING:'Ese edificio ya se está mejorando.',NOTHING_TO_COLLECT:'Todavía no hay producción disponible.',NOT_PRODUCING:'Este edificio no genera recursos.',NOT_READY:'La mejora aún no ha terminado.'};
const human=(v:string)=>errors[v]??v.replaceAll('_',' ').toLowerCase();
function remaining(iso?:string|null){if(!iso)return'';const ms=new Date(iso).getTime()-Date.now();if(ms<=0)return'LISTO';const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);return h?`${h}h ${m}m`:m?`${m}m ${s}s`:`${s}s`;}
export function BastionPanel({active,snapshot,onClose,onSnapshot}:{active:string;snapshot:Snapshot;onClose:()=>void;onSnapshot:(s:Snapshot)=>void}){
 const visible=active==='bastion';const[data,setData]=useState<any>(null),[busy,setBusy]=useState(''),[error,setError]=useState('');const[,setClockTick]=useState(0);
 async function load(){if(!visible)return;setError('');try{const r=await fetch(`${apiUrl}/v1/bastion`,{headers:auth()});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'LOAD_FAILED');setData(j);}catch(e:any){setError(human(e.message));}}
 async function refreshSnapshot(){const r=await fetch(`${apiUrl}/v1/me/snapshot`,{headers:auth()});if(r.ok)onSnapshot(await r.json());}
 useEffect(()=>{void load();},[visible]);
 useEffect(()=>{if(!visible)return;const id=window.setInterval(()=>setClockTick(v=>v+1),1000);return()=>window.clearInterval(id);},[visible]);
 async function post(code:string,kind:'upgrade'|'complete'|'collect'){setBusy(`${code}:${kind}`);setError('');try{const r=await fetch(`${apiUrl}/v1/bastion/${code}/${kind}`,{method:'POST',headers:action()});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'ACTION_FAILED');await Promise.all([load(),refreshSnapshot()]);}catch(e:any){setError(human(e.message));}finally{setBusy('')}}
 if(!visible)return null;const buildings=data?.buildings??[];const upgrading=buildings.filter((b:any)=>b.upgrade_finishes_at).length;const producing=buildings.filter((b:any)=>b.production_resource&&num(b.base_production_per_hour)>0).length;
 return <section className="module-overlay bastion-premium-overlay" aria-label="Bastión"><header><div><Castle/><span><small>BASE PERSONAL</small><strong>Mi Bastión</strong></span></div><button onClick={onClose}><X/></button></header>{error&&<div className="module-error">{error}</div>}{!data?<div className="bastion-loading"><LoaderCircle/><b>Cartografiando tu Bastión…</b></div>:<>
  <section className="bastion-overview"><div><small>FORTALEZA DEL HÉROE</small><h2>{snapshot.character?.name}</h2><p>Los edificios producen y mejoran con reloj del servidor. Entrar al Bastión no restaura HP, MP ni energía de forma instantánea.</p></div><div className="bastion-stats"><span><Hammer/><b>{upgrading}</b> mejoras</span><span><Mountain/><b>{producing}</b> productores</span></div></section>
  <div className="bastion-landscape"><div className="bastion-sky"><i/><i/><i/></div><div className="bastion-ground"/><Trees className="bastion-tree tree-a"/><Trees className="bastion-tree tree-b"/>{buildings.map((b:any,index:number)=>{const meta=labels[b.building_code]??{name:b.name_es??b.building_code,Icon:Castle,zone:'utility'};const Icon=meta.Icon;const time=remaining(b.upgrade_finishes_at);const ready=time==='LISTO';const production=Boolean(b.production_resource)&&num(b.base_production_per_hour)>0;return <article className={`bastion-building zone-${meta.zone} building-${b.building_code} ${b.upgrade_finishes_at?'upgrading':''}`} style={{'--slot':index} as any} key={b.building_code}><button className="building-structure" type="button" aria-label={meta.name}><span className="building-roof"/><span className="building-body"><Icon/></span><span className="building-light"/></button><div className="building-info"><div><b>{b.name_es??meta.name}</b><small>Nivel {b.level}/{b.max_level}</small></div>{b.upgrade_finishes_at?<span className={ready?'ready':''}><Clock3/>{time}</span>:production?<span><Sparkles/>{num(b.base_production_per_hour)*Math.max(1,num(b.level))}/h</span>:null}</div><div className="building-actions">{production&&!b.upgrade_finishes_at&&<button disabled={Boolean(busy)} onClick={()=>post(b.building_code,'collect')}>RECOGER</button>}{b.upgrade_finishes_at?<button className={ready?'ready':''} disabled={Boolean(busy)||!ready} onClick={()=>post(b.building_code,'complete')}>{ready?'COMPLETAR':time}</button>:<button disabled={Boolean(busy)||num(b.level)>=num(b.max_level)} onClick={()=>post(b.building_code,'upgrade')}><Hammer/>MEJORAR</button>}</div></article>})}</div>
  <section className="bastion-regeneration"><div><HeartStat label="HP" value={snapshot.character?.hp} max={snapshot.character?.hp_max} seconds={120}/><HeartStat label="MP" value={snapshot.character?.mp} max={snapshot.character?.mp_max} seconds={90}/><HeartStat label="ENERGÍA" value={snapshot.character?.energy} max={snapshot.character?.energy_max} seconds={180}/></div><small>Regeneración calculada por servidor · el reloj local del teléfono no cambia los tiempos.</small></section>
 </>}</section>;
}
function HeartStat({label,value,max,seconds}:{label:string;value?:number;max?:number;seconds:number}){const v=num(value),m=num(max);return <span><b>{label}</b><i><em style={{width:`${Math.max(0,Math.min(100,v/Math.max(1,m)*100))}%`}}/></i><small>{v}/{m} · +1 cada {seconds}s</small></span>}
