'use client';

import { useEffect, useState } from 'react';
import { Activity, Bolt, Flag, Flame, Heart, LoaderCircle, Shield, Skull, Sparkles, Swords, Target, X, Zap } from 'lucide-react';
import type { Snapshot } from './GameHome';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
const auth=()=>({authorization:`Bearer ${sessionStorage.getItem('nr_session')??''}`});
const action=()=>({...auth(),'content-type':'application/json','idempotency-key':crypto.randomUUID()});
const num=(v:unknown)=>Number(v??0);
const pct=(v:number,m:number)=>`${Math.max(0,Math.min(100,(v/Math.max(1,m))*100))}%`;
const errors:Record<string,string>={NO_ENERGY:'No tienes energía suficiente. Se regenera con el tiempo del servidor.',COMBAT_ALREADY_ACTIVE:'Recuperando tu combate activo…',COMBAT_FINISHED:'Este combate ya terminó.',COMBAT_NOT_FOUND:'No se encontró el combate activo.',SKILL_COOLDOWN:'Esa habilidad aún está en enfriamiento.',NO_MP:'No tienes suficiente maná.',SKILL_LOCKED:'Esa habilidad todavía está bloqueada.',LOAD_FAILED:'No se pudo comprobar tu combate activo.',ABANDON_ERROR:'No se pudo abandonar el combate.'};
const errorText=(v:string)=>errors[v]??v.replaceAll('_',' ').toLowerCase();
const effectNames:Record<string,string>={bleed:'Sangrado',burn:'Quemadura',poison:'Veneno',freeze:'Congelado',stun:'Aturdido',silence:'Silenciado',shield:'Escudo',attack_up:'Ataque +',evasion_up:'Evasión +',block_up:'Bloqueo +',defense_down:'Defensa -',magic_resist_down:'Resistencia -',damage_taken_up:'Vulnerable'};
const effectIcon=(type:string)=>['bleed','burn','poison'].includes(type)?Flame:['shield','block_up'].includes(type)?Shield:['freeze','stun','silence'].includes(type)?Zap:Activity;

export function CombatPanel({active,snapshot,onClose,onSnapshot}:{active:string;snapshot:Snapshot;onClose:()=>void;onSnapshot:(s:Snapshot)=>void}){
 const visible=active==='adventure';
 const[state,setState]=useState<any>(null),[skills,setSkills]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[busy,setBusy]=useState(false),[checkingActive,setCheckingActive]=useState(false),[confirmAbandon,setConfirmAbandon]=useState(false),[error,setError]=useState(''),[flash,setFlash]=useState<any>(null);
 const character=snapshot.character;
 const usable=skills.filter((s:any)=>s.unlocked);
 async function get(path:string){const r=await fetch(`${apiUrl}${path}`,{headers:auth()});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'LOAD_FAILED');return j;}
 async function refreshSnapshot(){const r=await fetch(`${apiUrl}/v1/me/snapshot`,{headers:auth()});if(r.ok)onSnapshot(await r.json());}
 async function loadSkills(){try{const j=await get('/v1/skills');setSkills((j.skills??[]).filter((s:any)=>s.unlocked));}catch{}}
 async function loadActiveCombat(){setCheckingActive(true);try{const j=await get('/v1/combat/active');if(j.combat){setState({combat:j.combat,enemy:j.enemy??{name_es:j.combat.enemy_name_es,max_hp:j.combat.enemy_max_hp,tier:j.combat.tier},resumed:true});setEvents(j.events??[]);}else{setState(null);setEvents([]);}setFlash(null);}catch(e:any){setError(errorText(e.message));}finally{setCheckingActive(false)}}
 useEffect(()=>{if(!visible)return;setError('');setConfirmAbandon(false);void Promise.all([loadSkills(),loadActiveCombat()]);},[visible]);
 async function start(){setBusy(true);setError('');try{const r=await fetch(`${apiUrl}/v1/combat/start`,{method:'POST',headers:action(),body:'{}'});const j=await r.json().catch(()=>({}));if(!r.ok){if(j.error==='COMBAT_ALREADY_ACTIVE'){await loadActiveCombat();return;}throw new Error(j.error??'COMBAT_ERROR');}const response=j.response??j;setState(response);setEvents([]);setFlash(null);await refreshSnapshot();}catch(e:any){setError(errorText(e.message));}finally{setBusy(false)}}
 async function abandon(){const combatId=state?.combat?.id;if(!combatId)return;setBusy(true);setError('');try{const r=await fetch(`${apiUrl}/v1/combat/${combatId}/abandon`,{method:'POST',headers:action(),body:'{}'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'ABANDON_ERROR');setState(null);setEvents([]);setFlash(null);setConfirmAbandon(false);await refreshSnapshot();}catch(e:any){setError(errorText(e.message));}finally{setBusy(false)}}
 async function act(skillId?:string){const combat=state?.combat;if(!combat?.id)return;setBusy(true);setError('');try{const r=await fetch(`${apiUrl}/v1/combat/${combat.id}/action`,{method:'POST',headers:action(),body:JSON.stringify(skillId?{skillId}:{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error??'ACTION_ERROR');const response=j.response??j;const log=await get(`/v1/combat/${combat.id}`);setState((old:any)=>({...old,...response,combat:log.combat,enemy:old?.enemy??{name_es:log.combat.enemy_name_es,max_hp:log.combat.enemy_max_hp,tier:log.combat.tier},resumed:false}));setEvents(log.events??[]);setFlash({player:response.playerEvent,enemy:response.enemyEvent,status:response.statusDamage});window.setTimeout(()=>setFlash(null),700);if(response.combat?.state!=='active')await refreshSnapshot();}catch(e:any){setError(errorText(e.message));}finally{setBusy(false)}}
 if(!visible)return null;
 const combat=state?.combat,enemy=state?.enemy;const cooldowns=(combat?.cooldowns??{}) as Record<string,number>;const playerEffects=Array.isArray(combat?.player_effects)?combat.player_effects:[];const enemyEffects=Array.isArray(combat?.enemy_effects)?combat.enemy_effects:[];
 return <section className="module-overlay combat-premium-overlay" aria-label="Combate">
  <header><div><Swords/><span><small>COMBATE DEL NEXO</small><strong>Aventura</strong></span></div><button onClick={onClose}><X/></button></header>
  {error&&<div className="module-error">{error}</div>}
  {checkingActive?<div className="combat-recovering"><LoaderCircle className="spin"/><b>Comprobando combate activo…</b><span>Si cerraste Telegram durante una pelea, volverás al mismo turno.</span></div>:!combat?<div className="combat-ready"><div className={`combat-portrait hero-art-${character?.class_id}`}><img src={`/art/classes/${character?.class_id??'warrior'}.svg`} alt=""/><span className="combat-aura"/></div><div className="combat-ready-copy"><small>REINO ACTUAL</small><h2>Busca un enemigo</h2><p>El servidor elegirá un rival apropiado para tu nivel y reino. Cada combate cuesta 1 energía.</p><div className="combat-resource"><Zap/><b>{character?.energy}/{character?.energy_max}</b><span>Energía</span></div></div><button className="module-primary combat-start" disabled={busy} onClick={start}>{busy?<LoaderCircle className="spin"/>:<Swords/>}{busy?'BUSCANDO RIVAL…':'INICIAR COMBATE'}</button></div>:
  <div className={`combat-live state-${combat.state}`}>
   {state?.resumed&&<div className="combat-resumed"><Activity/><span><b>Combate recuperado</b><small>Continúa desde el turno {combat.turn_number} o abandona la pelea.</small></span></div>}
   <div className="combat-arena-stage"><div className="combat-stage-glow"/><div className="combatant player"><img src={`/art/classes/${character?.class_id??'warrior'}.svg`} alt="Héroe"/><div className="combat-name"><small>{character?.class_id?.toUpperCase()}</small><b>{character?.name}</b></div>{flash?.enemy?.damage>0&&<span className="floating-damage incoming">-{flash.enemy.damage}</span>}</div><div className="combat-vs"><Swords/></div><div className="combatant enemy"><img src="/art/enemies/ash-beast.svg" alt="Enemigo"/><div className="combat-name"><small>{String(enemy?.tier??combat.tier??'normal').toUpperCase()}</small><b>{enemy?.name_es??combat.enemy_name_es??'Bestia del Nexo'}</b></div>{flash?.player?.damage>0&&<span className={`floating-damage ${flash.player.critical?'critical':''}`}>-{flash.player.damage}</span>}</div></div>
   <div className="combat-vitals-grid"><div className="combat-vital player"><div><Heart/><b>{combat.player_hp}/{character?.hp_max}</b></div><i><span style={{width:pct(num(combat.player_hp),num(character?.hp_max))}}/></i><div className="combat-mana"><Sparkles/><b>{combat.player_mp}/{character?.mp_max}</b></div></div><div className="combat-vital enemy"><div><Skull/><b>{combat.enemy_hp}/{enemy?.max_hp??combat.enemy_max_hp}</b></div><i><span style={{width:pct(num(combat.enemy_hp),num(enemy?.max_hp??combat.enemy_max_hp))}}/></i><div className="enemy-tier"><Target/>{enemy?.tier??combat.tier??'normal'}</div></div></div>
   <div className="combat-effects-row"><EffectList title="Héroe" effects={playerEffects}/><EffectList title="Enemigo" effects={enemyEffects}/></div>
   {combat.state==='active'?<><div className="combat-skill-grid"><button className="skill-button basic" disabled={busy} onClick={()=>act()}><Swords/><span><b>Ataque</b><small>Sin coste</small></span></button>{usable.map((skill:any)=>{const cd=num(cooldowns[skill.id]),mp=num(skill.mp_cost),lockedMp=num(combat.player_mp)<mp;return <button key={skill.id} className={`skill-button type-${skill.damage_type}`} disabled={busy||cd>0||lockedMp} onClick={()=>act(skill.id)}><Bolt/><span><b>{skill.name_es}</b><small>{mp} MP · {num(skill.power_ratio).toFixed(2)}×</small></span>{cd>0&&<em>{cd}</em>}{lockedMp&&cd===0&&<em>MP</em>}</button>})}</div><div className="combat-turn-info"><span>Turno {combat.turn_number}</span><span>{busy?'Resolviendo acción…':'Elige una acción'}</span></div></>:<div className={`combat-finish ${combat.state}`}><TrophyIcon state={combat.state}/><h2>{combat.state==='victory'?'VICTORIA':'DERROTA'}</h2><p>{combat.state==='victory'?'Botín, EXP y progresión LiveOps se resolvieron en el servidor.':'HP se regenerará con tiempo real del servidor.'}</p><button className="module-primary" onClick={()=>{setState(null);setEvents([]);setFlash(null)}}>CONTINUAR</button></div>}
   {combat.state==='active'&&(confirmAbandon?<div className="combat-abandon-confirm"><p>Abandonar conserva tu HP y MP actuales. La energía gastada no se devuelve.</p><div><button type="button" disabled={busy} onClick={()=>setConfirmAbandon(false)}>SEGUIR LUCHANDO</button><button type="button" className="danger" disabled={busy} onClick={abandon}>{busy?<LoaderCircle className="spin"/>:<Flag/>}{busy?'ABANDONANDO…':'CONFIRMAR HUIDA'}</button></div></div>:<button type="button" className="combat-abandon" disabled={busy} onClick={()=>setConfirmAbandon(true)}><Flag/>ABANDONAR COMBATE</button>)}
   <div className="combat-history"><div className="combat-history-title"><Activity/><b>Registro del combate</b></div>{events.slice(-8).reverse().map((e:any)=><article key={e.id}><span>{e.actor}</span><b>{e.payload?.skillName??e.event_type.replaceAll('_',' ')}</b><small>{e.payload?.damage?`${e.payload.damage} daño`:e.payload?.healed?`${e.payload.healed} curación`:e.payload?.quantity?`${e.payload.quantity} ${e.payload.resource}`:''}</small></article>)}</div>
  </div>}
 </section>;
}

function EffectList({title,effects}:{title:string;effects:any[]}){return <div className="effect-list"><small>{title}</small><div>{effects.length===0?<span className="effect-empty">Sin estados</span>:effects.map((e:any,i:number)=>{const Icon=effectIcon(e.type);return <span className={`effect-chip effect-${e.type}`} key={`${e.type}-${i}`}><Icon/>{effectNames[e.type]??e.type.replaceAll('_',' ')}<b>{num(e.turns)}</b></span>})}</div></div>}
function TrophyIcon({state}:{state:string}){return state==='victory'?<Target/>:<Skull/>}
