'use client';

import { useEffect, useMemo, useState } from 'react';
import { Backpack, BookOpen, Castle, CircleDot, Crown, Gift, Hammer, Medal, ScrollText, Shield, ShoppingBag, Sparkles, Swords, Trophy, Users, X } from 'lucide-react';
import type { Snapshot } from './GameHome';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
const authHeaders=(json=false)=>({authorization:`Bearer ${sessionStorage.getItem('nr_session')??''}`,...(json?{'content-type':'application/json'}:{})});
const keyHeaders=(json=false)=>({...authHeaders(json),'idempotency-key':crypto.randomUUID()});
const signatureSkill:Record<string,string>={warrior:'warrior_cleave',mage:'mage_bolt',archer:'archer_shot',assassin:'assassin_slash'};
const modulePath:Record<string,string>={inventory:'/v1/inventory',quests:'/v1/quests',bastion:'/v1/bastion',crafting:'/v1/crafting/recipes',events:'/v1/events',battlepass:'/v1/battle-pass',shop:'/v1/shop',arena:'/v1/arena/me',referrals:'/v1/referrals',codex:'/v1/codex',achievements:'/v1/achievements',professions:'/v1/professions',daily:'/v1/daily-rewards',companions:'/v1/companions',clan:'/v1/clan/me'};
const titleMap:Record<string,string>={adventure:'Aventura',inventory:'Inventario',quests:'Misiones',bastion:'Mi Bastión',clan:'Clan',crafting:'Crafting',events:'Eventos',battlepass:'Battle Pass',shop:'Tienda',arena:'Arena',referrals:'Referidos',codex:'Codex',achievements:'Logros',professions:'Profesiones',daily:'Recompensa diaria',companions:'Mascotas y Monturas'};

export function GameModulePanel({active,snapshot,onClose,onSnapshot}:{active:string;snapshot:Snapshot;onClose:()=>void;onSnapshot:(s:Snapshot)=>void}){
 const [data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const character=snapshot.character;
 async function refreshSnapshot(){const r=await fetch(`${apiUrl}/v1/me/snapshot`,{headers:authHeaders()});if(r.ok)onSnapshot(await r.json());}
 async function load(){if(active==='home')return;setError('');const path=modulePath[active];if(!path){setData(null);return;}const r=await fetch(`${apiUrl}${path}`,{headers:authHeaders()});if(!r.ok){setError('No se pudo cargar este módulo.');return;}setData(await r.json());}
 useEffect(()=>{void load()},[active]);
 const events=useMemo(()=>Array.isArray(data?.events)?data.events.slice(-6):[],[data]);
 async function post(path:string,body?:unknown){setBusy(true);setError('');try{const r=await fetch(`${apiUrl}${path}`,{method:'POST',headers:keyHeaders(body!==undefined),body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error??'ACTION_FAILED');await load();await refreshSnapshot();return j;}catch(e:any){setError(e.message??'ACTION_FAILED')}finally{setBusy(false)}}
 async function startCombat(){setBusy(true);setError('');try{const r=await fetch(`${apiUrl}/v1/combat/start`,{method:'POST',headers:keyHeaders(true),body:'{}'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.response??j);}catch(e:any){setError(e.message??'COMBAT_ERROR')}finally{setBusy(false)}}
 async function combatAction(skillId?:string){const combat=data?.combat??data?.response?.combat;if(!combat?.id)return;setBusy(true);try{const r=await fetch(`${apiUrl}/v1/combat/${combat.id}/action`,{method:'POST',headers:keyHeaders(true),body:JSON.stringify(skillId?{skillId}:{})});const j=await r.json();if(!r.ok)throw new Error(j.error);const state=j.response??j;const log=await fetch(`${apiUrl}/v1/combat/${combat.id}`,{headers:authHeaders()}).then(x=>x.json());setData({...state,...log});if(state.combat?.state!=='active')await refreshSnapshot();}catch(e:any){setError(e.message??'ACTION_ERROR')}finally{setBusy(false)}}
 if(active==='home')return null;
 const title=titleMap[active]??'Nexo';const Icon=active==='adventure'?Swords:active==='inventory'?Backpack:active==='quests'?ScrollText:active==='bastion'?Castle:active==='crafting'?Hammer:active==='events'?Sparkles:active==='battlepass'?Trophy:active==='shop'?ShoppingBag:active==='arena'?Medal:active==='referrals'?Users:active==='codex'?BookOpen:active==='achievements'?Crown:active==='daily'?Gift:active==='companions'?CircleDot:Users;const combat=data?.combat??data?.response?.combat;const enemy=data?.enemy??data?.response?.enemy;
 return <section className="module-overlay" aria-label={title}>
  <header><div><Icon/><span><small>MÓDULO ACTIVO</small><strong>{title}</strong></span></div><button onClick={onClose}><X/></button></header>{error&&<div className="module-error">{error}</div>}
  {active==='adventure'&&<div className="combat-module">{!combat?<><div className="combat-stage"><div className="combat-runes"/><div className="player-figure"/><div className="enemy-figure"/><div className="versus">VS</div></div><button className="module-primary" disabled={busy} onClick={startCombat}><Swords/>{busy?'Buscando enemigo…':'INICIAR COMBATE'}</button></>:<><div className="combat-stage live"><div className="player-figure"/><div className="enemy-figure"/><span className="enemy-name">{enemy?.name_es??combat.enemy_name_es??'Enemigo del Nexo'}</span></div><div className="combat-bars"><label>Héroe <i><b style={{width:`${Math.max(0,Math.min(100,(Number(combat.player_hp)/(character?.hp_max||1))*100))}%`}}/></i><span>{combat.player_hp} HP</span></label><label>Enemigo <i><b style={{width:`${Math.max(0,Math.min(100,(Number(combat.enemy_hp)/(Number(enemy?.max_hp??combat.enemy_max_hp)||1))*100))}%`}}/></i><span>{combat.enemy_hp} HP</span></label></div>{combat.state==='active'?<div className="combat-actions"><button disabled={busy} onClick={()=>combatAction()}><Shield/>Ataque</button><button disabled={busy} onClick={()=>combatAction(signatureSkill[character?.class_id??'warrior'])}><Sparkles/>Habilidad</button></div>:<div className={`combat-result ${combat.state}`}>{combat.state==='victory'?'VICTORIA':'DERROTA'}<button onClick={()=>setData(null)}>Continuar</button></div>}<div className="combat-log">{events.map((e:any)=><p key={e.id}><b>{e.actor}</b> · {e.event_type} {e.payload?.damage?`— ${e.payload.damage} daño`:''}</p>)}</div></>}</div>}
  {active==='inventory'&&<div className="module-list">{(data?.items??[]).length===0?<div className="empty-state"><Backpack/><b>Mochila vacía</b><span>El loot aparecerá aquí.</span></div>:(data.items??[]).map((i:any)=><article key={i.id} className={`rarity-${i.rarity}`}><div className="item-glyph"/><div><b>{i.name_es}</b><span>{i.item_type} · {i.rarity} · +{i.enhancement_level}</span></div>{i.equipped_slot&&<em>{i.equipped_slot}</em>}</article>)}</div>}
  {active==='quests'&&<div className="module-list">{(data?.quests??[]).map((q:any)=><article key={q.id}><ScrollText/><div><b>{q.title_es}</b><span>{q.category} · Nv. {q.min_level}</span><p>{q.description_es}</p></div><button disabled={busy||q.status!=='available'} onClick={()=>post(`/v1/quests/${q.id}/accept`)}>{q.status==='available'?'Aceptar':q.status}</button></article>)}</div>}
  {active==='bastion'&&<div className="bastion-map">{(data?.buildings??[]).map((b:any,index:number)=>{const finish=b.upgrade_finishes_at?new Date(b.upgrade_finishes_at).getTime():0;const ready=finish>0&&finish<=Date.now();return <article key={b.building_code} style={{'--i':index} as any}><div className="building-art"><Castle/></div><b>{b.name_es??b.building_code}</b><span>Nivel {b.level}</span>{b.upgrade_finishes_at?<button disabled={busy||!ready} onClick={()=>post(`/v1/bastion/${b.building_code}/complete`)}>{ready?'Completar':'Mejorando…'}</button>:<button disabled={busy} onClick={()=>post(`/v1/bastion/${b.building_code}/upgrade`)}><Hammer/>Mejorar</button>}</article>})}</div>}
  {active==='crafting'&&<div className="module-list">{(data?.recipes??[]).map((r:any)=><article key={r.id}><Hammer/><div><b>{r.name_es}</b><span>{r.profession_id} · Nv. {r.min_profession_level}</span><p>{r.gold_cost} oro · {r.duration_seconds}s</p></div><button disabled={busy} onClick={()=>post(`/v1/crafting/${r.id}/start`)}>Fabricar</button></article>)}</div>}
  {active==='events'&&<div className="module-list">{(data?.events??[]).map((e:any)=><article key={e.id}><Sparkles/><div><b>{e.name_es}</b><span>{e.event_type} · {e.status??'próximo'}</span><p>{e.description_es}</p></div></article>)}</div>}
  {active==='battlepass'&&<><div className="season-banner"><Trophy/><div><small>TEMPORADA</small><b>{data?.season?.config?.name??'Ecos del Nexo'}</b><span>Nivel {data?.progress?.level??1} · {data?.progress?.xp??0} XP</span></div></div><div className="reward-track">{(data?.rewards??[]).slice(0,24).map((r:any)=><article key={`${r.level}-${r.track}`}><span>Nv. {r.level}</span><b>{r.track==='premium'?'PREMIUM':'GRATIS'}</b><button disabled={busy||r.claimed||(data?.progress?.level??1)<r.level} onClick={()=>post(`/v1/battle-pass/${r.level}/${r.track}/claim`)}>{r.claimed?'Reclamado':'Reclamar'}</button></article>)}</div></>}
  {active==='shop'&&<><div className="module-disclaimer">Los créditos Premium son moneda interna del juego y no son retirables como dinero.</div><div className="shop-grid">{(data?.items??[]).map((i:any)=><article key={i.id}><ShoppingBag/><b>{i.name_es}</b><span>{i.category}</span><strong>{i.price_credits} créditos</strong><button disabled={busy} onClick={()=>post(`/v1/shop/${i.id}/purchase`)}>Comprar</button></article>)}</div></>}
  {active==='arena'&&<div className="arena-card"><Medal/><small>LIGA</small><h2>{String(data?.profile?.league??'bronze').toUpperCase()}</h2><b>{data?.profile?.rating??1000} rating</b><span>{data?.profile?.wins??0} victorias · {data?.profile?.losses??0} derrotas</span><button className="module-primary" disabled={busy} onClick={()=>post('/v1/arena/match')}>BUSCAR RIVAL</button></div>}
  {active==='referrals'&&<div className="referral-card"><Users/><h2>Invita héroes</h2><code>{data?.profile?.referral_code??snapshot.referral?.referral_code}</code><p>La atribución se registra una sola vez en backend y bloquea autorreferidos.</p><b>{(data?.invited??[]).length} invitados</b></div>}
  {active==='codex'&&<><div className="collection-progress"><BookOpen/><b>{data?.discovered??0}/{data?.total??0}</b><span>entradas descubiertas</span></div><div className="module-list">{(data?.entries??[]).map((e:any)=><article key={e.id}><BookOpen/><div><b>{e.name_es}</b><span>{e.category} · {Number(e.progress)>0?'Descubierto':'???'}</span><p>{Number(e.progress)>0?e.lore_es:'Sigue explorando para revelar esta entrada.'}</p></div></article>)}</div></>}
  {active==='achievements'&&<div className="module-list">{(data?.achievements??[]).map((a:any)=><article key={a.id}><Trophy/><div><b>{a.secret&&!a.completed_at?'Logro secreto':a.name_es}</b><span>{a.category}</span><p>{String(a.progress)}/{a.target}</p></div>{a.completed_at&&<em>COMPLETO</em>}</article>)}</div>}
  {active==='professions'&&<div className="module-list">{(data?.professions??[]).map((p:any)=><article key={p.id}><Hammer/><div><b>{p.name_es}</b><span>Nivel {p.level} · {p.gathering?'Recolección':'Producción'}</span><p>{String(p.experience)} EXP</p></div></article>)}</div>}
  {active==='daily'&&<><div className="daily-hero"><Gift/><h2>Racha {data?.state?.streak??0}</h2><p>Día {data?.state?.cycle_day??1} del ciclo</p><button className="module-primary" disabled={busy} onClick={()=>post('/v1/daily-rewards/claim')}>RECLAMAR</button></div><div className="daily-grid">{(data?.rewards??[]).slice(0,7).map((r:any)=><article key={r.cycle_day}><b>Día {r.cycle_day}</b><span>{r.special?'Cofre especial':'Recompensa'}</span></article>)}</div></>}
  {active==='companions'&&<><h3 className="module-heading">Mascotas</h3><div className="shop-grid">{(data?.pets??[]).map((p:any)=><article key={p.id}><CircleDot/><b>{p.name_es}</b><span>{p.rarity}</span><strong>{p.level?`Nv. ${p.level}`:'No obtenida'}</strong></article>)}</div><h3 className="module-heading">Monturas</h3><div className="shop-grid">{(data?.mounts??[]).map((m:any)=><article key={m.id}><Crown/><b>{m.name_es}</b><span>{m.rarity}</span><strong>{m.unlocked_at?'Desbloqueada':'Bloqueada'}</strong></article>)}</div></>}
  {active==='clan'&&<div className="clan-module"><div className="clan-emblem"><Users/></div><h3>{data?.clan?`[${data.clan.tag}] ${data.clan.name}`:'Sin clan'}</h3><p>{data?.clan?'Base de clan, raid, tesorería y contribuciones sincronizadas por servidor.':'Busca o crea un clan para desbloquear progresión cooperativa.'}</p>{data?.clan&&<div className="clan-stats"><span><b>{(data.buildings??[]).length}</b> edificios</span><span><b>{(data.members??[]).length}</b> miembros</span><span><b>{(data.raids??[]).filter((r:any)=>r.status==='active').length}</b> raids activos</span></div>}</div>}
 </section>;
}
