'use client';

import { useEffect, useState } from 'react';
import { Bell, Languages, MonitorCog, Music, ShieldCheck, SlidersHorizontal, Volume2, X } from 'lucide-react';
import { applyPreferences, loadPreferences, savePreferences, setAmbientMusic, type ClientPreferences } from '../lib/clientPreferences';

const apiUrl=process.env.NEXT_PUBLIC_API_URL??'http://localhost:3001';
const auth=(json=false)=>({authorization:`Bearer ${sessionStorage.getItem('nr_session')??''}`,...(json?{'content-type':'application/json'}:{})});
const defaults:ClientPreferences=loadPreferences();

export function SettingsPanel({active,onClose}:{active:string;onClose:()=>void}){
 const visible=active==='settings';const [prefs,setPrefs]=useState<ClientPreferences>(defaults),[notifications,setNotifications]=useState<Record<string,boolean>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!visible)return;setMessage('');void(async()=>{try{const r=await fetch(`${apiUrl}/v1/settings`,{headers:auth()});if(!r.ok)return;const j=await r.json();const s=j.settings??{};const next:ClientPreferences={language:s.language==='en'?'en':'es',graphicsPreset:['auto','low','medium','high'].includes(s.graphics_preset)?s.graphics_preset:'auto',musicVolume:Number(s.music_volume??.35),effectsVolume:Number(s.effects_volume??.55),muted:Boolean(s.muted),reducedMotion:Boolean(s.reduced_motion)};setPrefs(next);setNotifications(j.notifications??{});savePreferences(next);}catch{}})();},[active]);
 function local(next:ClientPreferences){setPrefs(next);savePreferences(next);applyPreferences(next);}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch(`${apiUrl}/v1/settings`,{method:'PUT',headers:auth(true),body:JSON.stringify(prefs)});if(!r.ok)throw new Error();savePreferences(prefs);setAmbientMusic(!prefs.muted&&prefs.musicVolume>0);setMessage(prefs.language==='en'?'Settings saved.':'Ajustes guardados.');}catch{setMessage(prefs.language==='en'?'Could not save settings.':'No se pudieron guardar los ajustes.');}finally{setBusy(false)}}
 async function toggleNotification(id:string){const next={...notifications,[id]:!notifications[id]};setNotifications(next);try{await fetch(`${apiUrl}/v1/settings/notifications`,{method:'PUT',headers:auth(true),body:JSON.stringify({[id]:next[id]})});}catch{}}
 if(!visible)return null;const en=prefs.language==='en';
 const notificationLabels:Record<string,[string,string]>={energy:['Energía lista','Energy ready'],crafting:['Crafting terminado','Crafting complete'],building:['Edificio terminado','Building complete'],boss:['Jefes y raids','Bosses and raids'],event:['Eventos','Events'],clan:['Clan','Clan'],reward:['Recompensas','Rewards']};
 return <section className="module-overlay settings-overlay" aria-label={en?'Settings':'Ajustes'}>
  <header><div><SlidersHorizontal/><span><small>{en?'PLAYER PREFERENCES':'PREFERENCIAS DEL JUGADOR'}</small><strong>{en?'Settings':'Ajustes'}</strong></span></div><button onClick={onClose}><X/></button></header>
  {message&&<div className="module-success">{message}</div>}
  <section className="settings-card"><div className="settings-title"><Languages/><div><b>{en?'Language':'Idioma'}</b><span>{en?'Interface and content language':'Idioma de interfaz y contenido'}</span></div></div><div className="segmented"><button className={prefs.language==='es'?'active':''} onClick={()=>local({...prefs,language:'es'})}>Español</button><button className={prefs.language==='en'?'active':''} onClick={()=>local({...prefs,language:'en'})}>English</button></div></section>
  <section className="settings-card"><div className="settings-title"><MonitorCog/><div><b>{en?'Graphics':'Gráficos'}</b><span>{en?'Choose quality for your device':'Elige calidad para tu dispositivo'}</span></div></div><div className="segmented four">{(['auto','low','medium','high'] as const).map(v=><button className={prefs.graphicsPreset===v?'active':''} key={v} onClick={()=>local({...prefs,graphicsPreset:v})}>{en?({auto:'Auto',low:'Low',medium:'Medium',high:'High'} as any)[v]:({auto:'Auto',low:'Bajo',medium:'Medio',high:'Alto'} as any)[v]}</button>)}</div><label className="setting-toggle"><span><ShieldCheck/>{en?'Reduce animations':'Reducir animaciones'}</span><input type="checkbox" checked={prefs.reducedMotion} onChange={e=>local({...prefs,reducedMotion:e.target.checked})}/></label></section>
  <section className="settings-card"><div className="settings-title"><Music/><div><b>{en?'Audio':'Sonido'}</b><span>{en?'Procedural ambience and interface feedback':'Ambiente procedural y feedback de interfaz'}</span></div></div><label className="range-row"><span><Music/>{en?'Music':'Música'}</span><input type="range" min="0" max="1" step="0.05" value={prefs.musicVolume} onChange={e=>local({...prefs,musicVolume:Number(e.target.value)})}/><b>{Math.round(prefs.musicVolume*100)}%</b></label><label className="range-row"><span><Volume2/>{en?'Effects':'Efectos'}</span><input type="range" min="0" max="1" step="0.05" value={prefs.effectsVolume} onChange={e=>local({...prefs,effectsVolume:Number(e.target.value)})}/><b>{Math.round(prefs.effectsVolume*100)}%</b></label><label className="setting-toggle"><span><Volume2/>{en?'Mute all':'Silenciar todo'}</span><input type="checkbox" checked={prefs.muted} onChange={e=>{const next={...prefs,muted:e.target.checked};local(next);setAmbientMusic(!next.muted&&next.musicVolume>0)}}/></label></section>
  <section className="settings-card"><div className="settings-title"><Bell/><div><b>{en?'Telegram notifications':'Notificaciones de Telegram'}</b><span>{en?'Only useful alerts. No spam.':'Solo avisos útiles. Sin spam.'}</span></div></div><div className="notification-grid">{Object.entries(notificationLabels).map(([id,[esLabel,enLabel]])=><label key={id}><span>{en?enLabel:esLabel}</span><input type="checkbox" checked={notifications[id]!==false} onChange={()=>toggleNotification(id)}/></label>)}</div></section>
  <button className="module-primary settings-save" disabled={busy} onClick={save}>{busy?(en?'SAVING…':'GUARDANDO…'):(en?'SAVE SETTINGS':'GUARDAR AJUSTES')}</button>
 </section>;
}
