begin;

alter table game.skill_definitions add column if not exists description_es text not null default '';
alter table game.skill_definitions add column if not exists description_en text not null default '';

update game.skill_definitions set description_es=case id
 when 'warrior_cleave' then 'Un tajo pesado que concentra la fuerza del Guerrero contra un único objetivo.'
 when 'warrior_guard' then 'Adopta una postura férrea y genera un escudo temporal para resistir el siguiente intercambio.'
 when 'warrior_breaker' then 'Golpe brutal que causa daño elevado y debilita temporalmente la defensa enemiga.'
 when 'warrior_rally' then 'Un grito de guerra que eleva el poder ofensivo durante varios turnos.'
 when 'warrior_execution' then 'Ataque de ejecución que se vuelve más letal cuando el enemigo está herido.'
 when 'warrior_aegis' then 'Invoca una égida ancestral que refuerza escudo y capacidad de bloqueo.'
 when 'warrior_bleed' then 'Corte profundo que deja una hemorragia activa durante varios turnos.'
 when 'warrior_ultimate' then 'Desata un impacto devastador con posibilidad de aturdir al objetivo.'
 when 'mage_bolt' then 'Descarga arcana rápida y eficiente para infligir daño mágico directo.'
 when 'mage_frost' then 'Encierra al objetivo en escarcha y puede congelarlo durante un turno.'
 when 'mage_burn' then 'Marca al enemigo con fuego arcano que sigue causando daño con el tiempo.'
 when 'mage_barrier' then 'Crea una barrera astral que absorbe daño durante los próximos turnos.'
 when 'mage_void' then 'Pulso del Vacío que causa gran daño mágico y puede silenciar al enemigo.'
 when 'mage_chain' then 'Ata al objetivo con energía celeste y reduce su resistencia mágica.'
 when 'mage_rewind' then 'Manipula el tiempo del combate y altera el ritmo de los enfriamientos.'
 when 'mage_ultimate' then 'Explosión arcana masiva que combina daño extremo con quemadura prolongada.'
 when 'archer_shot' then 'Disparo preciso y fiable que aprovecha al máximo la puntería del Arquero.'
 when 'archer_pierce' then 'Flecha perforante que atraviesa parte de la protección del enemigo.'
 when 'archer_poison' then 'Impregna una flecha con veneno para causar daño progresivo.'
 when 'archer_evasion' then 'Movimiento evasivo que aumenta notablemente la posibilidad de esquivar.'
 when 'archer_volley' then 'Una lluvia concentrada de proyectiles que inflige daño físico elevado.'
 when 'archer_mark' then 'Marca al enemigo para hacerlo más vulnerable a los ataques posteriores.'
 when 'archer_ricochet' then 'Proyectil rúnico de alto poder diseñado para castigar objetivos resistentes.'
 when 'archer_ultimate' then 'Disparo definitivo de enorme potencia con una gran bonificación crítica.'
 when 'assassin_slash' then 'Corte veloz desde las sombras, ideal para iniciar cadenas ofensivas.'
 when 'assassin_bleed' then 'Abre una herida profunda que continúa drenando vida durante varios turnos.'
 when 'assassin_smoke' then 'Se oculta tras un velo de humo y aumenta fuertemente su evasión.'
 when 'assassin_combo' then 'Cadena de ataques rápidos que recompensa mantener la presión ofensiva.'
 when 'assassin_silence' then 'Golpe preciso que puede bloquear temporalmente las habilidades del rival.'
 when 'assassin_execute' then 'Ataque de remate con enorme bonificación contra enemigos debilitados.'
 when 'assassin_night' then 'Danza de cuchillas que combina daño alto con una bonificación crítica.'
 when 'assassin_ultimate' then 'Eclipse sangriento de potencia extrema que además provoca hemorragia severa.'
 else description_es end,
 description_en=case id
 when 'warrior_cleave' then 'A heavy cleave that focuses the Warrior’s strength on a single target.'
 when 'warrior_guard' then 'Takes an iron stance and gains a temporary shield.'
 when 'warrior_breaker' then 'A brutal strike that deals heavy damage and lowers enemy defense.'
 when 'warrior_rally' then 'A war cry that raises offensive power for several turns.'
 when 'warrior_execution' then 'An execution strike that becomes deadlier against wounded enemies.'
 when 'warrior_aegis' then 'Summons an ancestral aegis that boosts shielding and block chance.'
 when 'warrior_bleed' then 'A deep cut that causes bleeding over several turns.'
 when 'warrior_ultimate' then 'A devastating impact with a chance to stun the target.'
 when 'mage_bolt' then 'A fast and efficient arcane blast that deals direct magic damage.'
 when 'mage_frost' then 'Traps the target in frost and may freeze it for one turn.'
 when 'mage_burn' then 'Marks the enemy with arcane fire that keeps dealing damage over time.'
 when 'mage_barrier' then 'Creates an astral barrier that absorbs incoming damage.'
 when 'mage_void' then 'A Void pulse that deals heavy magic damage and may silence the enemy.'
 when 'mage_chain' then 'Binds the target with celestial energy and lowers magic resistance.'
 when 'mage_rewind' then 'Manipulates combat time and shifts cooldown pacing.'
 when 'mage_ultimate' then 'A massive arcane explosion combining extreme damage with burning.'
 when 'archer_shot' then 'A precise, reliable shot that rewards the Archer’s accuracy.'
 when 'archer_pierce' then 'A piercing arrow that bypasses part of the target’s protection.'
 when 'archer_poison' then 'Coats an arrow in venom to deal damage over time.'
 when 'archer_evasion' then 'An evasive movement that greatly raises dodge chance.'
 when 'archer_volley' then 'A concentrated volley that deals heavy physical damage.'
 when 'archer_mark' then 'Marks the enemy and makes it more vulnerable to follow-up attacks.'
 when 'archer_ricochet' then 'A high-powered runic projectile built to punish durable targets.'
 when 'archer_ultimate' then 'A devastating final shot with a large critical bonus.'
 when 'assassin_slash' then 'A fast shadow slash ideal for opening offensive chains.'
 when 'assassin_bleed' then 'Opens a deep wound that keeps draining health.'
 when 'assassin_smoke' then 'Vanishes behind smoke and sharply raises evasion.'
 when 'assassin_combo' then 'A rapid attack chain that rewards sustained pressure.'
 when 'assassin_silence' then 'A precise strike that can temporarily disable enemy skills.'
 when 'assassin_execute' then 'A finishing strike with a huge bonus against weakened enemies.'
 when 'assassin_night' then 'A blade dance combining high damage with a critical bonus.'
 when 'assassin_ultimate' then 'An extreme blood eclipse that also inflicts severe bleeding.'
 else description_en end;

commit;
