import type { Hono } from 'hono';
import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;
type RequirePlayerId = (authorization?: string) => Promise<string>;

function adminIds(){return new Set((process.env.ADMIN_IDS??'').split(',').map(v=>v.trim()).filter(Boolean));}
async function requireAdmin(c:any,sql:Sql,requirePlayerId:RequirePlayerId){const playerId=await requirePlayerId(c.req.header('authorization'));const [p]=await sql`select id,telegram_user_id from game.players where id=${playerId}`;if(!p||!adminIds().has(String(p.telegram_user_id)))throw new Error('ADMIN_REQUIRED');return{playerId,telegramId:Number(p.telegram_user_id)};}
async function audit(sql:Sql,telegramId:number,action:string,targetType:string,targetId:string|null,before:any,after:any,reason?:string){await sql`insert into game.admin_audit_log(admin_telegram_id,action,target_type,target_id,before_state,after_state,reason) values(${telegramId},${action},${targetType},${targetId},${before?sql.json(before):null},${after?sql.json(after):null},${reason??null})`;}

export function registerAdminRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
 app.get('/v1/admin/overview',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const [stats]=await sql`select (select count(*) from game.players)::int players,(select count(*) from game.characters)::int characters,(select count(*) from game.clans)::int clans,(select count(*) from game.combat_sessions where state='active')::int active_combats,(select count(*) from game.market_listings where status='active')::int market_listings,(select count(*) from game.player_notifications where delivered_at is null)::int pending_notifications`;return c.json({stats,admin:a.telegramId});});
 app.get('/v1/admin/players',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const q=(c.req.query('q')??'').trim();const rows=await sql`select p.id,p.telegram_user_id,p.username,p.display_name,p.is_banned,p.created_at,ch.name character_name,ch.level,ch.power from game.players p left join game.characters ch on ch.player_id=p.id where ${q===''?sql`true`:sql`lower(p.display_name) like ${'%'+q.toLowerCase()+'%'} or lower(coalesce(p.username,'')) like ${'%'+q.toLowerCase()+'%'} or p.telegram_user_id::text=${q}`} order by p.created_at desc limit 100`;return c.json({players:rows});});
 app.post('/v1/admin/players/:playerId/ban',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const target=c.req.param('playerId');const body=await c.req.json().catch(()=>({}));const banned=Boolean(body.banned);const [before]=await sql`select id,is_banned from game.players where id=${target}`;if(!before)return c.json({error:'PLAYER_NOT_FOUND'},404);const [after]=await sql`update game.players set is_banned=${banned},updated_at=now() where id=${target} returning id,is_banned`;await audit(sql,a.telegramId,banned?'player.ban':'player.unban','player',target,before,after,String(body.reason??''));return c.json({player:after});});
 app.post('/v1/admin/players/:playerId/grant',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const target=c.req.param('playerId');const body=await c.req.json().catch(()=>({}));const currency=String(body.currency??'gold').slice(0,40);const amount=Math.trunc(Number(body.amount??0));if(!Number.isFinite(amount)||amount===0||Math.abs(amount)>1000000)return c.json({error:'INVALID_AMOUNT'},400);const out=await sql.begin(async tx=>{const [ch]=await tx`select id from game.characters where player_id=${target} for update`;if(!ch)throw new Error('CHARACTER_NOT_FOUND');const [before]=await tx`select amount from game.resources where character_id=${ch.id} and resource_code=${currency} for update`;const current=Number(before?.amount??0);const next=current+amount;if(next<0)throw new Error('NEGATIVE_BALANCE');await tx`insert into game.resources(character_id,resource_code,amount) values(${ch.id},${currency},${next}) on conflict(character_id,resource_code) do update set amount=excluded.amount,updated_at=now()`;await tx`insert into game.economy_ledger(player_id,character_id,currency,delta,balance_after,reason,reference_id) values(${target},${ch.id},${currency},${amount},${next},'admin_adjustment',${String(a.telegramId)})`;return{before:current,after:next}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);await audit(sql,a.telegramId,'player.resource.adjust','player',target,{currency,amount:out.before},{currency,amount:out.after},String(body.reason??''));return c.json({currency,balance:out.after});});
 app.put('/v1/admin/config/:key',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const key=c.req.param('key');const body=await c.req.json().catch(()=>null);if(body===null)return c.json({error:'INVALID_JSON'},400);const [before]=await sql`select value from game.runtime_config where key=${key}`;await sql`insert into game.runtime_config(key,value) values(${key},${sql.json(body)}) on conflict(key) do update set value=excluded.value,updated_at=now()`;await audit(sql,a.telegramId,'config.update','runtime_config',key,before?.value??null,body);return c.json({key,value:body});});
 app.put('/v1/admin/features/:key',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const key=c.req.param('key');const body=await c.req.json().catch(()=>({}));if(['real_money_withdrawals','web3'].includes(key)&&body.enabled===true)return c.json({error:'FEATURE_REQUIRES_EXTERNAL_INFRASTRUCTURE_AND_EXPLICIT_AUTHORIZATION'},409);const [before]=await sql`select enabled,config from game.feature_flags where key=${key}`;await sql`insert into game.feature_flags(key,enabled,config) values(${key},${Boolean(body.enabled)},${sql.json(body.config??{})}) on conflict(key) do update set enabled=excluded.enabled,config=excluded.config,updated_at=now()`;await audit(sql,a.telegramId,'feature.update','feature_flag',key,before??null,{enabled:Boolean(body.enabled),config:body.config??{}});return c.json({key,enabled:Boolean(body.enabled)});});
 app.get('/v1/admin/audit',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const rows=await sql`select * from game.admin_audit_log order by created_at desc limit 200`;return c.json({audit:rows});});
}
