import type { Hono } from 'hono';
import type postgres from 'postgres';

type Sql=ReturnType<typeof postgres>;
type RequirePlayerId=(authorization?:string)=>Promise<string>;
const n=(v:unknown)=>Number(v??0);
function adminIds(){return new Set((process.env.ADMIN_IDS??'').split(',').map(v=>v.trim()).filter(Boolean));}
async function requireAdmin(c:any,sql:Sql,requirePlayerId:RequirePlayerId){const playerId=await requirePlayerId(c.req.header('authorization'));const[p]=await sql`select id,telegram_user_id from game.players where id=${playerId}`;if(!p||!adminIds().has(String(p.telegram_user_id)))throw new Error('ADMIN_REQUIRED');return{playerId,telegramId:Number(p.telegram_user_id)};}
async function audit(sql:any,telegramId:number,action:string,targetType:string,targetId:string|null,before:any,after:any,reason?:string){await sql`insert into game.admin_audit_log(admin_telegram_id,action,target_type,target_id,before_state,after_state,reason) values(${telegramId},${action},${targetType},${targetId},${before?sql.json(before):null},${after?sql.json(after):null},${reason??null})`;}

export function registerAdminRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
 app.get('/v1/admin/overview',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const[stats]=await sql`select (select count(*) from game.players)::int players,(select count(*) from game.characters)::int characters,(select count(*) from game.clans)::int clans,(select count(*) from game.combat_sessions where state='active')::int active_combats,(select count(*) from game.market_listings where status='active')::int market_listings,(select count(*) from game.player_notifications where delivered_at is null)::int pending_notifications,(select count(*) from game.event_instances where status='active' and ends_at>now())::int live_events,(select count(*) from game.clan_wars where status='active' and ends_at>now())::int live_clan_wars`;return c.json({stats,admin:a.telegramId});});

 app.get('/v1/admin/analytics',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const days=Math.max(7,Math.min(90,Math.floor(n(c.req.query('days')||30))));const[summary]=await sql`select (select count(distinct player_id) from game.analytics_events where created_at>=now()-interval '24 hours')::int dau,(select count(distinct player_id) from game.analytics_events where created_at>=now()-interval '7 days')::int wau,(select count(distinct player_id) from game.analytics_events where created_at>=now()-(${days}||' days')::interval)::int mau,(select count(*) from game.analytics_events where event_name='session_start' and created_at>=now()-interval '24 hours')::int sessions_24h,(select count(*) from game.combat_sessions where finished_at>=now()-interval '24 hours')::int combats_24h,(select count(*) from game.crafting_jobs where claimed_at>=now()-interval '24 hours')::int crafts_24h`;
  const funnel=await sql`select event_name,count(*)::int events,count(distinct player_id)::int players from game.analytics_events where created_at>=now()-(${days}||' days')::interval and event_name in ('session_start','screen_view','character_created','combat_start','combat_victory','quest_claim','craft_claim','shop_purchase') group by event_name order by events desc`;
  const screens=await sql`select properties->>'screen' screen,count(*)::int views,count(distinct player_id)::int players from game.analytics_events where event_name='screen_view' and created_at>=now()-(${days}||' days')::interval group by properties->>'screen' order by views desc limit 30`;
  const retention=await sql`with cohort as (select id,created_at from game.players where created_at>=now()-interval '30 days'), activity as (select distinct player_id,created_at::date day from game.analytics_events where player_id is not null and created_at>=now()-interval '31 days') select count(*)::int cohort,(count(*) filter(where exists(select 1 from activity a where a.player_id=c.id and a.day between (c.created_at+interval '1 day')::date and (c.created_at+interval '2 days')::date)))::int d1,(count(*) filter(where exists(select 1 from activity a where a.player_id=c.id and a.day between (c.created_at+interval '3 days')::date and (c.created_at+interval '4 days')::date)))::int d3,(count(*) filter(where exists(select 1 from activity a where a.player_id=c.id and a.day between (c.created_at+interval '7 days')::date and (c.created_at+interval '8 days')::date)))::int d7 from cohort c`;
  return c.json({days,summary,funnel,screens,retention});});

 app.get('/v1/admin/economy',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const resources=await sql`select resource_code,count(*)::int holders,sum(amount)::bigint total,max(amount)::bigint max_balance from game.resources group by resource_code order by total desc limit 40`;const ledger=await sql`select currency,reason,count(*)::int operations,sum(delta)::bigint net_delta,sum(abs(delta))::bigint volume from game.economy_ledger where created_at>=now()-interval '24 hours' group by currency,reason order by volume desc limit 50`;const[earn]=await sql`select count(*)::int holders,coalesce(sum(internal_credits),0)::bigint total,coalesce(max(internal_credits),0)::bigint max_balance from game.earn_balances`;const[market]=await sql`select count(*) filter(where status='active')::int active,count(*) filter(where status='sold')::int sold,coalesce(sum(price) filter(where status='sold'),0)::bigint sold_volume from game.market_listings`;return c.json({resources,ledger,earn,market});});

 app.get('/v1/admin/events',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const definitions=await sql`select * from game.event_definitions order by event_type,id`;const instances=await sql`select i.*,d.name_es,d.event_type,(select count(*) from game.event_contributions ec where ec.event_instance_id=i.id)::int contributors,coalesce((select sum(contribution) from game.event_contributions ec where ec.event_instance_id=i.id),0)::bigint contribution from game.event_instances i join game.event_definitions d on d.id=i.event_id order by i.starts_at desc limit 100`;return c.json({definitions,instances,serverTime:new Date().toISOString()});});
 app.post('/v1/admin/events/:eventId/launch',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const eventId=c.req.param('eventId');const body=await c.req.json().catch(()=>({}));const duration=Math.max(1,Math.min(336,Math.floor(n(body.durationHours)||24)));const startDelay=Math.max(0,Math.min(168,Math.floor(n(body.startDelayHours)||0)));const[definition]=await sql`select id,name_es,enabled from game.event_definitions where id=${eventId}`;if(!definition||!definition.enabled)return c.json({error:'EVENT_NOT_FOUND'},404);const[instance]=await sql`insert into game.event_instances(event_id,starts_at,ends_at,status,state) values(${eventId},now()+(${startDelay}||' hours')::interval,now()+(${startDelay+duration}||' hours')::interval,${startDelay>0?'scheduled':'active'},${sql.json(body.state??{})}) returning *`;await audit(sql,a.telegramId,'event.launch','event_instance',String(instance.id),null,instance,String(body.reason??''));return c.json({instance},201);});
 app.post('/v1/admin/events/:instanceId/finish',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const instanceId=c.req.param('instanceId');const[before]=await sql`select * from game.event_instances where id=${instanceId}`;if(!before)return c.json({error:'EVENT_INSTANCE_NOT_FOUND'},404);const[after]=await sql`update game.event_instances set status='finished',ends_at=least(ends_at,now()) where id=${instanceId} returning *`;await audit(sql,a.telegramId,'event.finish','event_instance',instanceId,before,after);return c.json({instance:after});});

 app.get('/v1/admin/clans',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const clans=await sql`select c.id,c.name,c.tag,c.level,c.experience,(select count(*) from game.clan_members m where m.clan_id=c.id)::int members,(select coalesce(sum(amount),0) from game.clan_treasury t where t.clan_id=c.id)::bigint treasury_total from game.clans c order by c.level desc,c.experience desc limit 100`;const wars=await sql`select w.*,a.name clan_a_name,b.name clan_b_name from game.clan_wars w join game.clans a on a.id=w.clan_a join game.clans b on b.id=w.clan_b order by w.starts_at desc limit 100`;return c.json({clans,wars});});

 app.get('/v1/admin/players',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const q=(c.req.query('q')??'').trim();const rows=await sql`select p.id,p.telegram_user_id,p.username,p.display_name,p.is_banned,p.created_at,ch.name character_name,ch.level,ch.power from game.players p left join game.characters ch on ch.player_id=p.id where ${q===''?sql`true`:sql`lower(p.display_name) like ${'%'+q.toLowerCase()+'%'} or lower(coalesce(p.username,'')) like ${'%'+q.toLowerCase()+'%'} or p.telegram_user_id::text=${q}`} order by p.created_at desc limit 100`;return c.json({players:rows});});
 app.post('/v1/admin/players/:playerId/ban',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const target=c.req.param('playerId');const body=await c.req.json().catch(()=>({}));const banned=Boolean(body.banned);const[before]=await sql`select id,is_banned from game.players where id=${target}`;if(!before)return c.json({error:'PLAYER_NOT_FOUND'},404);const[after]=await sql`update game.players set is_banned=${banned},updated_at=now() where id=${target} returning id,is_banned`;await audit(sql,a.telegramId,banned?'player.ban':'player.unban','player',target,before,after,String(body.reason??''));return c.json({player:after});});
 app.post('/v1/admin/players/:playerId/grant',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const target=c.req.param('playerId');const body=await c.req.json().catch(()=>({}));const currency=String(body.currency??'gold').slice(0,40);const amount=Math.trunc(Number(body.amount??0));if(!Number.isFinite(amount)||amount===0||Math.abs(amount)>1000000)return c.json({error:'INVALID_AMOUNT'},400);const out=await sql.begin(async tx=>{const[ch]=await tx`select id from game.characters where player_id=${target} for update`;if(!ch)throw new Error('CHARACTER_NOT_FOUND');const[before]=await tx`select amount from game.resources where character_id=${ch.id} and resource_code=${currency} for update`;const current=Number(before?.amount??0);const next=current+amount;if(next<0)throw new Error('NEGATIVE_BALANCE');await tx`insert into game.resources(character_id,resource_code,amount) values(${ch.id},${currency},${next}) on conflict(character_id,resource_code) do update set amount=excluded.amount,updated_at=now()`;await tx`insert into game.economy_ledger(player_id,character_id,currency,delta,balance_after,reason,reference_id) values(${target},${ch.id},${currency},${amount},${next},'admin_adjustment',${String(a.telegramId)})`;return{before:current,after:next}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);await audit(sql,a.telegramId,'player.resource.adjust','player',target,{currency,amount:out.before},{currency,amount:out.after},String(body.reason??''));return c.json({currency,balance:out.after});});
 app.put('/v1/admin/config/:key',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const key=c.req.param('key');const body=await c.req.json().catch(()=>null);if(body===null)return c.json({error:'INVALID_JSON'},400);const[before]=await sql`select value from game.runtime_config where key=${key}`;await sql`insert into game.runtime_config(key,value) values(${key},${sql.json(body)}) on conflict(key) do update set value=excluded.value,updated_at=now()`;await audit(sql,a.telegramId,'config.update','runtime_config',key,before?.value??null,body);return c.json({key,value:body});});
 app.put('/v1/admin/features/:key',async c=>{let a;try{a=await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const key=c.req.param('key');const body=await c.req.json().catch(()=>({}));if(['real_money_withdrawals','web3'].includes(key)&&body.enabled===true)return c.json({error:'FEATURE_REQUIRES_EXTERNAL_INFRASTRUCTURE_AND_EXPLICIT_AUTHORIZATION'},409);const[before]=await sql`select enabled,config from game.feature_flags where key=${key}`;await sql`insert into game.feature_flags(key,enabled,config) values(${key},${Boolean(body.enabled)},${sql.json(body.config??{})}) on conflict(key) do update set enabled=excluded.enabled,config=excluded.config,updated_at=now()`;await audit(sql,a.telegramId,'feature.update','feature_flag',key,before??null,{enabled:Boolean(body.enabled),config:body.config??{}});return c.json({key,enabled:Boolean(body.enabled)});});
 app.get('/v1/admin/audit',async c=>{try{await requireAdmin(c,sql,requirePlayerId)}catch{return c.json({error:'FORBIDDEN'},403)}const rows=await sql`select * from game.admin_audit_log order by created_at desc limit 200`;return c.json({audit:rows});});
}
