import type { Hono } from 'hono';
import type postgres from 'postgres';
import { chooseEnemyAction, resolveDamage, tickCooldowns, type CombatStats } from './combatEngine.js';

type Sql=ReturnType<typeof postgres>;
type RequirePlayerId=(authorization?:string)=>Promise<string>;
type Effect={type:string;turns?:number;value?:number;power?:number;chance?:number;threshold?:number;bonus?:number;sourcePower?:number};
const n=(v:unknown)=>Number(v??0);
const rolls=()=>({hit:Math.random(),crit:Math.random(),block:Math.random(),variance:Math.random()});
async function receipt(tx:any,p:string,op:string,key?:string){if(!key||key.length>120)throw new Error('IDEMPOTENCY_KEY_REQUIRED');const rows=await tx`insert into game.action_receipts(player_id,operation,idempotency_key) values(${p},${op},${key}) on conflict(player_id,operation,idempotency_key) do nothing returning id`;if(rows[0])return{id:rows[0].id,duplicate:false,response:null};const [old]=await tx`select response from game.action_receipts where player_id=${p} and operation=${op} and idempotency_key=${key}`;return{id:null,duplicate:true,response:old?.response??{}};}
function asEffects(v:any):Effect[]{return Array.isArray(v)?v.filter(x=>x&&typeof x==='object'&&typeof x.type==='string').map(x=>({...x,turns:Math.max(1,n(x.turns)||1)})):[];}
function effectTotal(effects:Effect[],type:string,key:'value'|'power'='value'){return effects.filter(e=>e.type===type).reduce((s,e)=>s+n(e[key]),0);}
function has(effects:Effect[],...types:string[]){return effects.some(e=>types.includes(e.type));}
function addEffect(target:Effect[],effect:Effect,sourcePower:number){const chance=effect.chance===undefined?1:n(effect.chance);if(Math.random()>chance)return;const normalized={...effect,turns:Math.max(1,n(effect.turns)||1),sourcePower};const existing=target.find(e=>e.type===normalized.type);if(existing){existing.turns=Math.max(n(existing.turns),n(normalized.turns));existing.value=Math.max(n(existing.value),n(normalized.value));existing.power=Math.max(n(existing.power),n(normalized.power));existing.sourcePower=Math.max(n(existing.sourcePower),sourcePower);}else target.push(normalized);}
function tickEffects(effects:Effect[],hp:number){let damage=0;const next:Effect[]=[];for(const e of effects){if(['bleed','burn','poison'].includes(e.type)){const dot=Math.max(1,Math.round(Math.max(8,n(e.sourcePower))*Math.max(.05,n(e.power)||.12)));damage+=dot;}const turns=Math.max(0,n(e.turns)-1);if(turns>0)next.push({...e,turns});}return{hp:Math.max(0,hp-damage),damage,effects:next};}
function tacticStats(row:any):CombatStats{let physical=n(row.physical_attack),magic=n(row.magic_attack),defense=n(row.defense),magicResistance=n(row.magic_resistance),crit=n(row.crit_chance),accuracy=n(row.accuracy),evasion=n(row.evasion),block=n(row.block_chance);const tactic=String(row.tactic??'balanced');if(tactic==='aggressive'){physical*=1.10;magic*=1.10;defense*=.95;magicResistance*=.95;crit+=.02;}else if(tactic==='defensive'){defense*=1.12;magicResistance*=1.12;block+=.04;}else if(tactic==='smart'){accuracy+=.05;crit+=.015;magic*=1.04;}else{physical*=1.03;magic*=1.03;defense*=1.03;magicResistance*=1.03;}return{physicalAttack:physical,magicAttack:magic,defense,magicResistance,critChance:crit,critDamage:n(row.crit_damage),accuracy,evasion,blockChance:block};}
function buffedPlayer(row:any,effects:Effect[]):CombatStats{const s=tacticStats(row);const attack=1+effectTotal(effects,'attack_up');return{...s,physicalAttack:s.physicalAttack*attack,magicAttack:s.magicAttack*attack,evasion:Math.min(.75,s.evasion+effectTotal(effects,'evasion_up')),blockChance:Math.min(.75,s.blockChance+effectTotal(effects,'block_up'))};}
function enemyDef(row:any,effects:Effect[]){return{defense:Math.max(0,n(row.enemy_defense)*(1-effectTotal(effects,'defense_down'))),magicResistance:Math.max(0,n(row.enemy_magic_resistance)*(1-effectTotal(effects,'magic_resist_down'))),evasion:.02,blockChance:.02};}
function enemyAtk(row:any):CombatStats{return{physicalAttack:n(row.enemy_attack),magicAttack:n(row.enemy_attack),defense:n(row.enemy_defense),magicResistance:n(row.enemy_magic_resistance),critChance:.05,critDamage:1.5,accuracy:1,evasion:.02,blockChance:.02};}
function applySkillEffects(skillEffects:Effect[],playerEffects:Effect[],enemyEffects:Effect[],sourcePower:number){for(const e of skillEffects){if(['shield','attack_up','evasion_up','block_up'].includes(e.type))addEffect(playerEffects,e,sourcePower);else if(['bleed','burn','poison','defense_down','magic_resist_down','freeze','stun','silence','damage_taken_up'].includes(e.type))addEffect(enemyEffects,e,sourcePower);}}

export function registerAdvancedCombatRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
 app.get('/v1/combat/active',async c=>{
  let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}
  const [combat]=await sql`select s.*,e.name_es enemy_name_es,e.name_en enemy_name_en,e.max_hp enemy_max_hp,e.visual_key,e.abilities,e.tier from game.combat_sessions s join game.characters ch on ch.id=s.character_id left join game.enemy_definitions e on e.id=s.enemy_id where ch.player_id=${p} and s.state='active' order by s.started_at desc limit 1`;
  if(!combat)return c.json({combat:null,enemy:null,events:[],serverTime:new Date().toISOString()});
  const events=await sql`select * from game.combat_events where combat_id=${combat.id} order by id`;
  return c.json({combat,enemy:{id:combat.enemy_id,name_es:combat.enemy_name_es,name_en:combat.enemy_name_en,max_hp:combat.enemy_max_hp,visual_key:combat.visual_key,abilities:combat.abilities,tier:combat.tier},events,serverTime:new Date().toISOString()});
 });

 app.post('/v1/combat/start',async c=>{
  let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const requested=body.enemyId?String(body.enemyId):null;
  const out=await sql.begin(async tx=>{const r=await receipt(tx,p,'combat.start',c.req.header('idempotency-key'));if(r.duplicate)return{duplicate:true,response:r.response};const [ch]=await tx`select * from game.characters where player_id=${p} for update`;if(!ch)throw new Error('CHARACTER_REQUIRED');const [active]=await tx`select id from game.combat_sessions where character_id=${ch.id} and state='active' limit 1`;if(active)throw new Error('COMBAT_ALREADY_ACTIVE');const [regen]=await tx`select game.regenerated_value(${ch.hp},${ch.hp_max},${ch.hp_regen_anchor},120,now()) hp,game.regenerated_value(${ch.mp},${ch.mp_max},${ch.mp_regen_anchor},90,now()) mp,game.regenerated_value(${ch.energy},${ch.energy_max},${ch.energy_regen_anchor},180,now()) energy`;if(n(regen.energy)<1)throw new Error('NO_ENERGY');let enemies:any[];if(requested)enemies=await tx`select * from game.enemy_definitions where id=${requested} and realm_id=${ch.current_realm_id} and enabled`;else enemies=await tx`select * from game.enemy_definitions where realm_id=${ch.current_realm_id} and enabled order by abs(level-${ch.level}),case tier when 'champion' then 0 when 'elite' then 1 else 2 end,random() limit 1`;const enemy=enemies[0];if(!enemy)throw new Error('ENEMY_NOT_FOUND');await tx`update game.characters set hp=${n(regen.hp)},mp=${n(regen.mp)},energy=${n(regen.energy)-1},energy_regen_anchor=now(),updated_at=now() where id=${ch.id}`;const [combat]=await tx`insert into game.combat_sessions(character_id,enemy_id,player_hp,player_mp,enemy_hp) values(${ch.id},${enemy.id},${n(regen.hp)},${n(regen.mp)},${enemy.max_hp}) returning *`;await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combat.id},1,'system','combat_started',${tx.json({enemyId:enemy.id,tier:enemy.tier})})`;const response={combat,enemy,regeneration:{hp:n(regen.hp),mp:n(regen.mp),energy:n(regen.energy)-1}};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response};}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out,201);
 });

 app.get('/v1/combat/:combatId',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const id=c.req.param('combatId');const [combat]=await sql`select s.*,e.name_es enemy_name_es,e.name_en enemy_name_en,e.max_hp enemy_max_hp,e.visual_key,e.abilities,e.tier from game.combat_sessions s join game.characters ch on ch.id=s.character_id left join game.enemy_definitions e on e.id=s.enemy_id where s.id=${id} and ch.player_id=${p}`;if(!combat)return c.json({error:'COMBAT_NOT_FOUND'},404);const events=await sql`select * from game.combat_events where combat_id=${id} order by id`;return c.json({combat,events});});

 app.post('/v1/combat/:combatId/abandon',async c=>{
  let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const combatId=c.req.param('combatId');
  const out=await sql.begin(async tx=>{
   const r=await receipt(tx,p,'combat.abandon',c.req.header('idempotency-key'));if(r.duplicate)return{duplicate:true,response:r.response};
   const [row]=await tx`select s.*,ch.hp_max,ch.mp_max from game.combat_sessions s join game.characters ch on ch.id=s.character_id where s.id=${combatId} and ch.player_id=${p} for update`;
   if(!row)throw new Error('COMBAT_NOT_FOUND');if(row.state!=='active')throw new Error('COMBAT_FINISHED');
   const hp=Math.max(0,Math.min(n(row.player_hp),n(row.hp_max))),mp=Math.max(0,Math.min(n(row.player_mp),n(row.mp_max)));
   await tx`update game.characters set hp=${hp},mp=${mp},hp_regen_anchor=now(),mp_regen_anchor=now(),updated_at=now() where id=${row.character_id}`;
   const [updated]=await tx`update game.combat_sessions set state='abandoned',finished_at=now(),updated_at=now() where id=${combatId} returning *`;
   await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${n(row.turn_number)},'player','combat_abandoned','{}'::jsonb)`;
   const response={combat:updated};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response};
  }).catch((e:Error)=>({error:e.message}));
  if('error'in out)return c.json({error:out.error},out.error==='COMBAT_NOT_FOUND'?404:409);return c.json(out);
 });

 app.post('/v1/combat/:combatId/action',async c=>{
  let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const combatId=c.req.param('combatId');const body=await c.req.json().catch(()=>({}));const skillId=body.skillId?String(body.skillId):null;
  const out=await sql.begin(async tx=>{
   const r=await receipt(tx,p,'combat.action',c.req.header('idempotency-key'));if(r.duplicate)return{duplicate:true,response:r.response};
   const [row]=await tx`select s.*,ch.level,ch.class_id,ch.player_id,ch.hp_max,ch.mp_max,st.*,coalesce(cp.tactic,'balanced') tactic,e.id enemy_definition_id,e.name_es,e.max_hp enemy_max_hp,e.attack enemy_attack,e.defense enemy_defense,e.magic_resistance enemy_magic_resistance,e.speed enemy_speed,e.abilities,e.tier from game.combat_sessions s join game.characters ch on ch.id=s.character_id join game.character_stats st on st.character_id=ch.id left join game.character_progression cp on cp.character_id=ch.id join game.enemy_definitions e on e.id=s.enemy_id where s.id=${combatId} and ch.player_id=${p} for update`;
   if(!row)throw new Error('COMBAT_NOT_FOUND');if(row.state!=='active')throw new Error('COMBAT_FINISHED');
   let playerEffects=asEffects(row.player_effects),enemyEffects=asEffects(row.enemy_effects);let playerHp=n(row.player_hp),enemyHp=n(row.enemy_hp),playerMp=n(row.player_mp);const playerTick=tickEffects(playerEffects,playerHp),enemyTick=tickEffects(enemyEffects,enemyHp);playerHp=playerTick.hp;enemyHp=enemyTick.hp;playerEffects=playerTick.effects;enemyEffects=enemyTick.effects;const turn=n(row.turn_number);
   if(playerTick.damage>0)await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${turn},'system','status_damage',${tx.json({target:'player',damage:playerTick.damage})})`;if(enemyTick.damage>0)await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${turn},'system','status_damage',${tx.json({target:'enemy',damage:enemyTick.damage})})`;
   let cds=tickCooldowns((row.cooldowns??{}) as Record<string,number>);let state='active';let playerEvent:any={};let enemyEvent:any=null;
   if(playerHp<=0){state='defeat';}else if(enemyHp<=0){state='victory';playerEvent={skillName:'Daño continuo',damage:enemyTick.damage};}else{
    let ratio=1,damageType:'physical'|'magic'='physical',mpCost=0,cooldown=0,skillName='Ataque básico';let skillEffects:Effect[]=[];if(skillId){const [skill]=await tx`select * from game.skill_definitions where id=${skillId} and class_id=${row.class_id} and unlock_level<=${row.level} and enabled`;if(!skill)throw new Error('SKILL_LOCKED');if(n(cds[skillId])>0)throw new Error('SKILL_COOLDOWN');if(playerMp<n(skill.mp_cost))throw new Error('NO_MP');ratio=n(skill.power_ratio);damageType=skill.damage_type==='magic'?'magic':'physical';mpCost=n(skill.mp_cost);cooldown=n(skill.cooldown_turns);skillName=skill.name_es;skillEffects=asEffects(skill.effects);if(cooldown>0)cds[skillId]=cooldown;}
    playerMp=Math.max(0,playerMp-mpCost);const attacker=buffedPlayer(row,playerEffects);const currentHpRatio=enemyHp/Math.max(1,n(row.enemy_max_hp));for(const e of skillEffects){if(e.type==='execute_bonus'&&currentHpRatio<=n(e.threshold))ratio*=1+n(e.value);if(e.type==='combo')ratio*=1+n(e.bonus);if(e.type==='cooldown_shift')cds=Object.fromEntries(Object.entries(cds).map(([id,v])=>[id,Math.max(0,n(v)+n(e.value))]).filter(([,v])=>n(v)>0));}
    const penEffect=skillEffects.find(e=>e.type==='penetration_bonus');const critEffect=skillEffects.find(e=>e.type==='crit_bonus');let damage=0;let resolved={damage:0,missed:false,critical:false,blocked:false};if(ratio>0){resolved=resolveDamage({attacker,defender:enemyDef(row,enemyEffects),type:damageType,powerRatio:ratio,penetration:penEffect?n(row.enemy_defense)*n(penEffect.value):0,guaranteedCritBonus:n(critEffect?.value),rolls:rolls()});damage=Math.round(resolved.damage*(1+effectTotal(enemyEffects,'damage_taken_up')));enemyHp=Math.max(0,enemyHp-damage);const leech=Math.min(damage,Math.round(damage*Math.max(0,n(row.lifesteal))));if(leech>0)playerHp=Math.min(n(row.hp_max),playerHp+leech);}
    applySkillEffects(skillEffects,playerEffects,enemyEffects,Math.max(attacker.physicalAttack,attacker.magicAttack));playerEvent={skillId,skillName,...resolved,damage,effects:skillEffects.map(e=>e.type)};await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${turn},'player','action',${tx.json(playerEvent)})`;
    if(enemyHp<=0)state='victory';else{
      const disabled=has(enemyEffects,'stun','freeze');const silenced=has(enemyEffects,'silence');let ability:any=disabled?{type:'disabled',ratio:0}:chooseEnemyAction({abilities:silenced?[{type:'basic',ratio:1}]:Array.isArray(row.abilities)?row.abilities:[{type:'basic'}],hp:enemyHp,maxHp:n(row.enemy_max_hp),rng:Math.random()});if(disabled)enemyEvent={ability:'disabled',skipped:true};else if(ability.type==='heal'){const healed=Math.max(1,Math.round(n(row.enemy_max_hp)*.16));enemyHp=Math.min(n(row.enemy_max_hp),enemyHp+healed);enemyEvent={ability:'heal',healed};}else{const defender=buffedPlayer(row,playerEffects);let ed=resolveDamage({attacker:enemyAtk(row),defender:{defense:defender.defense,magicResistance:defender.magicResistance,evasion:defender.evasion,blockChance:defender.blockChance},type:ability.type==='magic'?'magic':'physical',powerRatio:n(ability.ratio)||1,rolls:rolls()});const shield=effectTotal(playerEffects,'shield');const final=Math.max(0,ed.damage-Math.round(shield));playerHp=Math.max(0,playerHp-final);enemyEvent={ability:ability.type,...ed,damage:final,absorbed:Math.max(0,ed.damage-final)};if(['bleed','burn','poison'].includes(String(ability.type))&&Math.random()<=n(ability.chance||.25))addEffect(playerEffects,{type:String(ability.type),power:.10,turns:3},n(row.enemy_attack));else if(ability.type==='curse'&&Math.random()<=n(ability.chance||.25))addEffect(playerEffects,{type:'damage_taken_up',value:.10,turns:2},n(row.enemy_attack));}
      await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${turn},'enemy','action',${tx.json(enemyEvent)})`;if(playerHp<=0)state='defeat';
    }
   }
   if(state==='victory'){const gold=12+n(row.level)*4+(row.tier==='elite'?12:0);const xp=20+n(row.level)*9+(row.tier==='elite'?18:0);await tx`insert into game.resources(character_id,resource_code,amount) values(${row.character_id},'gold',${gold}) on conflict(character_id,resource_code) do update set amount=game.resources.amount+excluded.amount,updated_at=now()`;await tx`update game.characters set experience=experience+${xp},hp=${playerHp},mp=${playerMp},hp_regen_anchor=now(),mp_regen_anchor=now(),updated_at=now() where id=${row.character_id}`;await tx`insert into game.combat_events(combat_id,turn_number,actor,event_type,payload) values(${combatId},${turn},'system','victory',${tx.json({gold,xp})})`;}
   if(state==='defeat')await tx`update game.characters set hp=0,mp=${playerMp},hp_regen_anchor=now(),mp_regen_anchor=now(),updated_at=now() where id=${row.character_id}`;
   const [updated]=await tx`update game.combat_sessions set player_hp=${playerHp},player_mp=${playerMp},enemy_hp=${enemyHp},player_effects=${tx.json(playerEffects)},enemy_effects=${tx.json(enemyEffects)},turn_number=turn_number+1,cooldowns=${tx.json(cds)},state=${state},finished_at=case when ${state}<>'active' then now() else null end,updated_at=now() where id=${combatId} returning *`;const response={combat:updated,playerEvent,enemyEvent,statusDamage:{player:playerTick.damage,enemy:enemyTick.damage}};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response};
  }).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out);
 });
}
