import type { Hono } from 'hono';
import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;
type RequirePlayerId = (authorization?: string) => Promise<string>;

export function registerExtraRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
  app.get('/v1/codex',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select d.*,coalesce(cc.progress,0)::int progress,cc.discovered_at from game.codex_entries d left join game.characters ch on ch.player_id=${p} left join game.character_codex cc on cc.character_id=ch.id and cc.codex_id=d.id order by d.category,d.name_es`;return c.json({entries:rows,total:rows.length,discovered:rows.filter((x:any)=>Number(x.progress)>0).length});});
  app.get('/v1/achievements',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select a.*,coalesce(ca.progress,0)::bigint progress,ca.completed_at,ca.claimed_at from game.achievement_definitions a join game.characters ch on ch.player_id=${p} left join game.character_achievements ca on ca.character_id=ch.id and ca.achievement_id=a.id where a.enabled order by a.category,a.id`;return c.json({achievements:rows});});
  app.get('/v1/professions',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select d.*,coalesce(pp.level,1)::int level,coalesce(pp.experience,0)::bigint experience,pp.specialization from game.profession_definitions d join game.characters ch on ch.player_id=${p} left join game.profession_progress pp on pp.character_id=ch.id and pp.profession_id=d.id where d.enabled order by d.gathering desc,d.id`;return c.json({professions:rows});});
  app.get('/v1/companions',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const pets=await sql`select d.*,cp.level,cp.experience,cp.equipped from game.pet_definitions d left join game.characters ch on ch.player_id=${p} left join game.character_pets cp on cp.character_id=ch.id and cp.pet_id=d.id where d.enabled order by d.rarity,d.id`;const mounts=await sql`select d.*,cm.equipped,cm.unlocked_at from game.mount_definitions d left join game.characters ch on ch.player_id=${p} left join game.character_mounts cm on cm.character_id=ch.id and cm.mount_id=d.id where d.enabled order by d.rarity,d.id`;return c.json({pets,mounts});});
  app.get('/v1/daily-rewards',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}await sql`insert into game.daily_reward_state(player_id) values(${p}) on conflict do nothing`;const [state]=await sql`select * from game.daily_reward_state where player_id=${p}`;const rewards=await sql`select * from game.daily_reward_definitions order by cycle_day`;return c.json({state,rewards,serverTime:new Date().toISOString()});});
  app.get('/v1/realms',async c=>{const rows=await sql`select * from game.realms where enabled order by sort_order`;return c.json({realms:rows});});
  app.get('/v1/skills',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select s.*,(s.unlock_level<=ch.level) unlocked from game.skill_definitions s join game.characters ch on ch.player_id=${p} where s.class_id=ch.class_id and s.enabled order by s.unlock_level,s.id`;return c.json({skills:rows});});
}
