import type { Hono } from 'hono';
import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;
type RequirePlayerId = (authorization?: string) => Promise<string>;
const n=(v:unknown)=>Number(v??0);
const key=(c:any)=>c.req.header('idempotency-key');

async function takeReceipt(tx:any,playerId:string,operation:string,idempotencyKey?:string){
  if(!idempotencyKey||idempotencyKey.length>120)throw new Error('IDEMPOTENCY_KEY_REQUIRED');
  const rows=await tx`insert into game.action_receipts(player_id,operation,idempotency_key) values(${playerId},${operation},${idempotencyKey}) on conflict(player_id,operation,idempotency_key) do nothing returning id`;
  if(rows[0])return{id:rows[0].id,duplicate:false,response:null};
  const [old]=await tx`select response from game.action_receipts where player_id=${playerId} and operation=${operation} and idempotency_key=${idempotencyKey}`;
  return{id:null,duplicate:true,response:old?.response??{}};
}

async function addResource(tx:any,characterId:string,resource:string,amount:number){
  const qty=Math.floor(Math.max(0,amount));
  if(!qty)return;
  await tx`insert into game.resources(character_id,resource_code,amount) values(${characterId},${resource},${qty}) on conflict(character_id,resource_code) do update set amount=game.resources.amount+excluded.amount,updated_at=now()`;
}

async function grantReward(tx:any,character:any,reward:any){
  const value=reward&&typeof reward==='object'?reward:{};
  await addResource(tx,character.id,'gold',n(value.gold));
  await addResource(tx,character.id,'materials',n(value.materials));
  await addResource(tx,character.id,'cosmetic_tokens',n(value.cosmetic_token??value.cosmetic_tokens));
  await addResource(tx,character.id,'crystals',n(value.crystals));
  await addResource(tx,character.id,'premium_credits',n(value.premium_credits));
  await addResource(tx,character.id,'stat_points',n(value.stat_points));
  await addResource(tx,character.id,'profession_tree_points',n(value.profession_tree_points));
  if(value.chest)await addResource(tx,character.id,`chest_${String(value.chest).replace(/[^a-z0-9_-]/gi,'').toLowerCase()||'basic'}`,1);
  if(n(value.xp)>0)await tx`update game.characters set experience=experience+${Math.floor(n(value.xp))},updated_at=now() where id=${character.id}`;
  if(n(value.energy)>0)await tx`update game.characters set energy=least(energy_max,energy+${Math.floor(n(value.energy))}),updated_at=now() where id=${character.id}`;
  const resources=value.resources&&typeof value.resources==='object'?value.resources:{};
  for(const [code,amount] of Object.entries(resources))await addResource(tx,character.id,String(code),n(amount));
  const itemId=typeof value.item==='string'?value.item:typeof value.item?.id==='string'?value.item.id:null;
  if(itemId){
    const [def]=await tx`select id from game.item_definitions where id=${itemId} and enabled`;
    if(def)await tx`insert into game.inventory_items(character_id,item_definition_id,quantity) values(${character.id},${itemId},${Math.max(1,n(value.quantity??value.item?.quantity??1))})`;
  }
}

export function registerExtraRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
  app.get('/v1/codex',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select d.*,coalesce(cc.progress,0)::int progress,cc.discovered_at from game.codex_entries d left join game.characters ch on ch.player_id=${p} left join game.character_codex cc on cc.character_id=ch.id and cc.codex_id=d.id order by d.category,d.name_es`;return c.json({entries:rows,total:rows.length,discovered:rows.filter((x:any)=>Number(x.progress)>0).length});});
  app.get('/v1/achievements',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select a.*,coalesce(ca.progress,0)::bigint progress,ca.completed_at,ca.claimed_at from game.achievement_definitions a join game.characters ch on ch.player_id=${p} left join game.character_achievements ca on ca.character_id=ch.id and ca.achievement_id=a.id where a.enabled order by a.category,a.id`;return c.json({achievements:rows});});
  app.get('/v1/professions',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select d.*,coalesce(pp.level,1)::int level,coalesce(pp.experience,0)::bigint experience,pp.specialization from game.profession_definitions d join game.characters ch on ch.player_id=${p} left join game.profession_progress pp on pp.character_id=ch.id and pp.profession_id=d.id where d.enabled order by d.gathering desc,d.id`;return c.json({professions:rows});});
  app.get('/v1/companions',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const pets=await sql`select d.*,cp.level,cp.experience,cp.equipped from game.pet_definitions d left join game.characters ch on ch.player_id=${p} left join game.character_pets cp on cp.character_id=ch.id and cp.pet_id=d.id where d.enabled order by d.rarity,d.id`;const mounts=await sql`select d.*,cm.equipped,cm.unlocked_at from game.mount_definitions d left join game.characters ch on ch.player_id=${p} left join game.character_mounts cm on cm.character_id=ch.id and cm.mount_id=d.id where d.enabled order by d.rarity,d.id`;return c.json({pets,mounts});});
  app.get('/v1/daily-rewards',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}await sql`insert into game.daily_reward_state(player_id) values(${p}) on conflict do nothing`;const [state]=await sql`select *,coalesce(last_claimed_at::date=current_date,false) claimed_today from game.daily_reward_state where player_id=${p}`;const rewards=await sql`select * from game.daily_reward_definitions order by cycle_day`;return c.json({state,rewards,serverTime:new Date().toISOString()});});
  app.get('/v1/realms',async c=>{const rows=await sql`select * from game.realms where enabled order by sort_order`;return c.json({realms:rows});});
  app.get('/v1/skills',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const rows=await sql`select s.*,(s.unlock_level<=ch.level) unlocked from game.skill_definitions s join game.characters ch on ch.player_id=${p} where s.class_id=ch.class_id and s.enabled order by s.unlock_level,s.id`;return c.json({skills:rows});});

  app.get('/v1/earn',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const [balance]=await sql`select internal_credits,updated_at from game.earn_balances where player_id=${p}`;const events=await sql`select id,source,amount,metadata,created_at from game.earn_events where player_id=${p} order by created_at desc limit 60`;return c.json({balance:balance??{internal_credits:0},events,withdrawable:false,mode:'internal'});});

  app.get('/v1/crafting/jobs',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const jobs=await sql`select j.*,r.name_es,r.name_en,r.outputs,r.profession_id from game.crafting_jobs j join game.characters ch on ch.id=j.character_id join game.crafting_recipes r on r.id=j.recipe_id where ch.player_id=${p} order by case when j.status='running' then 0 else 1 end,j.finishes_at desc limit 40`;return c.json({jobs,serverTime:new Date().toISOString()});});

  app.post('/v1/battle-pass/:level/:track/claim-enhanced',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const level=n(c.req.param('level'));const track=c.req.param('track');if(!['free','premium'].includes(track)||level<1)return c.json({error:'INVALID_REWARD'},400);const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'battlepass.claim.enhanced',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [season]=await tx`select id from game.battle_pass_seasons where now() between starts_at and ends_at order by starts_at desc limit 1`;if(!season)throw new Error('NO_SEASON');await tx`insert into game.battle_pass_progress(season_id,player_id) values(${season.id},${p}) on conflict do nothing`;const [progress]=await tx`select * from game.battle_pass_progress where season_id=${season.id} and player_id=${p} for update`;if(n(progress.level)<level)throw new Error('LEVEL_LOCKED');if(track==='premium'&&!progress.premium_unlocked)throw new Error('PREMIUM_REQUIRED');const [rw]=await tx`select reward from game.battle_pass_rewards where season_id=${season.id} and level=${level} and track=${track}`;if(!rw)throw new Error('REWARD_NOT_FOUND');const inserted=await tx`insert into game.battle_pass_claims(season_id,player_id,level,track) values(${season.id},${p},${level},${track}) on conflict do nothing returning level`;if(!inserted[0])throw new Error('ALREADY_CLAIMED');const [ch]=await tx`select * from game.characters where player_id=${p} for update`;if(!ch)throw new Error('CHARACTER_REQUIRED');await grantReward(tx,ch,rw.reward);const response={claimed:true,reward:rw.reward};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/shop/:itemId/purchase-enhanced',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const itemId=c.req.param('itemId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'shop.purchase.enhanced',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [item]=await tx`select * from game.shop_items where id=${itemId} and enabled`;const [ch]=await tx`select * from game.characters where player_id=${p} for update`;if(!item||!ch)throw new Error('ITEM_NOT_FOUND');const contents=item.contents??{};if(contents.battle_pass_premium){const [season]=await tx`select id from game.battle_pass_seasons where now() between starts_at and ends_at order by starts_at desc limit 1`;if(!season)throw new Error('NO_SEASON');await tx`insert into game.battle_pass_progress(season_id,player_id) values(${season.id},${p}) on conflict do nothing`;const [bp]=await tx`select premium_unlocked from game.battle_pass_progress where season_id=${season.id} and player_id=${p} for update`;if(bp?.premium_unlocked)throw new Error('ALREADY_OWNED')}
    if(contents.pet){const [owned]=await tx`select 1 from game.character_pets where character_id=${ch.id} and pet_id=${String(contents.pet)}`;if(owned)throw new Error('ALREADY_OWNED')}
    if(contents.mount){const [owned]=await tx`select 1 from game.character_mounts where character_id=${ch.id} and mount_id=${String(contents.mount)}`;if(owned)throw new Error('ALREADY_OWNED')}
    if(contents.skin){const code=`skin_${String(contents.skin).replace(/[^a-z0-9_-]/gi,'').toLowerCase()}`;const [owned]=await tx`select amount from game.resources where character_id=${ch.id} and resource_code=${code}`;if(n(owned?.amount)>0)throw new Error('ALREADY_OWNED')}
    const [credits]=await tx`select amount from game.resources where character_id=${ch.id} and resource_code='premium_credits' for update`;if(n(credits?.amount)<n(item.price_credits))throw new Error('INSUFFICIENT_CREDITS');await tx`update game.resources set amount=amount-${n(item.price_credits)},updated_at=now() where character_id=${ch.id} and resource_code='premium_credits'`;await tx`insert into game.shop_purchases(player_id,shop_item_id,credits_spent,idempotency_key) values(${p},${item.id},${n(item.price_credits)},${key(c)})`;
    if(contents.battle_pass_premium){const [season]=await tx`select id from game.battle_pass_seasons where now() between starts_at and ends_at order by starts_at desc limit 1`;await tx`update game.battle_pass_progress set premium_unlocked=true,updated_at=now() where season_id=${season.id} and player_id=${p}`}
    if(contents.pet)await tx`insert into game.character_pets(character_id,pet_id) values(${ch.id},${String(contents.pet)}) on conflict do nothing`;
    if(contents.mount)await tx`insert into game.character_mounts(character_id,mount_id) values(${ch.id},${String(contents.mount)}) on conflict do nothing`;
    if(contents.skin)await addResource(tx,ch.id,`skin_${String(contents.skin).replace(/[^a-z0-9_-]/gi,'').toLowerCase()}`,1);
    if(n(contents.warehouse_tabs)>0)await addResource(tx,ch.id,'warehouse_tabs',n(contents.warehouse_tabs));
    const response={purchased:true,item:item.id,contents:item.contents};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/daily-rewards/claim-enhanced',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'daily.claim.enhanced',key(c));if(r.duplicate)return{duplicate:true,response:r.response};await tx`insert into game.daily_reward_state(player_id) values(${p}) on conflict do nothing`;const [state]=await tx`select *,coalesce(last_claimed_at::date=current_date,false) claimed_today from game.daily_reward_state where player_id=${p} for update`;if(state.claimed_today)throw new Error('ALREADY_CLAIMED_TODAY');const [rw]=await tx`select * from game.daily_reward_definitions where cycle_day=${state.cycle_day}`;const [ch]=await tx`select * from game.characters where player_id=${p} for update`;if(!rw||!ch)throw new Error('REWARD_NOT_FOUND');await grantReward(tx,ch,rw.reward);const nextDay=n(state.cycle_day)>=30?1:n(state.cycle_day)+1;await tx`update game.daily_reward_state set streak=streak+1,cycle_day=${nextDay},last_claimed_at=now(),updated_at=now() where player_id=${p}`;const response={claimed:true,day:state.cycle_day,reward:rw.reward};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/quests/:questId/claim',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const questId=c.req.param('questId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'quest.claim',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [row]=await tx`select qp.status,qd.rewards,ch.* from game.quest_progress qp join game.quest_definitions qd on qd.id=qp.quest_id join game.characters ch on ch.id=qp.character_id where ch.player_id=${p} and qp.quest_id=${questId} for update`;if(!row)throw new Error('QUEST_NOT_FOUND');if(row.status==='claimed')throw new Error('ALREADY_CLAIMED');if(row.status!=='completed')throw new Error('QUEST_NOT_COMPLETE');await grantReward(tx,row,row.rewards);await tx`update game.quest_progress set status='claimed',updated_at=now() where character_id=${row.id} and quest_id=${questId}`;const response={claimed:true,reward:row.rewards};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/achievements/:achievementId/claim',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const achievementId=c.req.param('achievementId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'achievement.claim',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [row]=await tx`select ca.completed_at,ca.claimed_at,a.rewards,ch.* from game.character_achievements ca join game.achievement_definitions a on a.id=ca.achievement_id join game.characters ch on ch.id=ca.character_id where ch.player_id=${p} and ca.achievement_id=${achievementId} for update`;if(!row)throw new Error('ACHIEVEMENT_NOT_FOUND');if(!row.completed_at)throw new Error('ACHIEVEMENT_NOT_COMPLETE');if(row.claimed_at)throw new Error('ALREADY_CLAIMED');await grantReward(tx,row,row.rewards);await tx`update game.character_achievements set claimed_at=now() where character_id=${row.id} and achievement_id=${achievementId}`;const response={claimed:true,reward:row.rewards};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/bastion/:code/collect',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const code=c.req.param('code');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'bastion.collect',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [b]=await tx`select b.*,d.production_resource,d.base_production_per_hour,d.base_capacity from game.bastion_buildings b join game.characters ch on ch.id=b.character_id join game.bastion_building_definitions d on d.code=b.building_code where ch.player_id=${p} and b.building_code=${code} for update`;if(!b||!b.production_resource||n(b.base_production_per_hour)<=0)throw new Error('NOT_PRODUCING');const elapsed=Math.max(0,(Date.now()-new Date(b.production_anchor).getTime())/3600000);const rate=n(b.base_production_per_hour)*Math.max(1,n(b.level));const capacity=n(b.base_capacity)*Math.max(1,n(b.level));const available=Math.min(capacity,n(b.production_stored)+Math.floor(elapsed*rate));if(available<1)throw new Error('NOTHING_TO_COLLECT');await addResource(tx,b.character_id,String(b.production_resource),available);await tx`update game.bastion_buildings set production_stored=0,production_anchor=now(),updated_at=now() where character_id=${b.character_id} and building_code=${code}`;const response={collected:available,resource:b.production_resource};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.get('/v1/clan/dashboard',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const [clan]=await sql`select c.*,m.role,m.contribution from game.clan_members m join game.clans c on c.id=m.clan_id where m.player_id=${p}`;const browse=await sql`select c.id,c.name,c.tag,c.description,c.level,c.experience,(select count(*) from game.clan_members m where m.clan_id=c.id)::int members from game.clans c order by c.level desc,c.experience desc limit 20`;if(!clan)return c.json({clan:null,browse});const buildings=await sql`select b.*,d.name_es,d.name_en,d.max_level,d.benefits from game.clan_buildings b join game.clan_building_definitions d on d.code=b.building_code where b.clan_id=${clan.id} order by b.building_code`;const members=await sql`select p.id,p.display_name,ch.name character_name,ch.level,ch.power,m.role,m.contribution from game.clan_members m join game.players p on p.id=m.player_id left join game.characters ch on ch.player_id=p.id where m.clan_id=${clan.id} order by case m.role when 'leader' then 0 when 'officer' then 1 else 2 end,m.contribution desc`;const raids=await sql`select * from game.clan_raids where clan_id=${clan.id} order by starts_at desc limit 10`;const treasury=await sql`select * from game.clan_treasury where clan_id=${clan.id} order by resource_code`;const activity=await sql`select a.*,p.display_name from game.clan_activity a left join game.players p on p.id=a.actor_player_id where a.clan_id=${clan.id} order by a.created_at desc limit 30`;return c.json({clan,buildings,members,raids,treasury,activity,browse});});

  app.post('/v1/clan/leave',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.leave',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [m]=await tx`select * from game.clan_members where player_id=${p} for update`;if(!m)throw new Error('CLAN_REQUIRED');const [count]=await tx`select count(*)::int total from game.clan_members where clan_id=${m.clan_id}`;if(m.role==='leader'&&n(count.total)>1)throw new Error('LEADER_CANNOT_LEAVE');if(m.role==='leader'){await tx`delete from game.clans where id=${m.clan_id}`}else{await tx`delete from game.clan_members where clan_id=${m.clan_id} and player_id=${p}`};const response={left:true};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/clan/settings',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const description=String(body.description??'').trim().slice(0,240);const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.settings',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [m]=await tx`select * from game.clan_members where player_id=${p}`;if(!m||m.role!=='leader')throw new Error('LEADER_REQUIRED');await tx`update game.clans set description=${description} where id=${m.clan_id}`;const response={saved:true,description};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},403);return c.json(out)});

  app.post('/v1/clan/buildings/:code/upgrade',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const code=c.req.param('code');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.building.upgrade',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [row]=await tx`select b.*,d.max_level,m.role from game.clan_buildings b join game.clan_members m on m.clan_id=b.clan_id and m.player_id=${p} join game.clan_building_definitions d on d.code=b.building_code where b.building_code=${code} for update`;if(!row||!['leader','officer'].includes(String(row.role)))throw new Error('CLAN_OFFICER_REQUIRED');if(row.upgrade_finishes_at&&new Date(row.upgrade_finishes_at).getTime()>Date.now())throw new Error('UPGRADE_RUNNING');if(n(row.level)>=n(row.max_level))throw new Error('MAX_LEVEL');const cost=500*n(row.level);const seconds=300*n(row.level);const [gold]=await tx`select amount from game.clan_treasury where clan_id=${row.clan_id} and resource_code='gold' for update`;if(n(gold?.amount)<cost)throw new Error('INSUFFICIENT_CLAN_GOLD');await tx`update game.clan_treasury set amount=amount-${cost},updated_at=now() where clan_id=${row.clan_id} and resource_code='gold'`;const [updated]=await tx`update game.clan_buildings set upgrade_finishes_at=now()+(${seconds}||' seconds')::interval,updated_at=now() where clan_id=${row.clan_id} and building_code=${code} returning upgrade_finishes_at`;const response={cost,finishesAt:updated.upgrade_finishes_at};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/clan/buildings/:code/complete',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const code=c.req.param('code');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.building.complete',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [row]=await tx`select b.*,m.role from game.clan_buildings b join game.clan_members m on m.clan_id=b.clan_id and m.player_id=${p} where b.building_code=${code} for update`;if(!row||!['leader','officer'].includes(String(row.role)))throw new Error('CLAN_OFFICER_REQUIRED');if(!row.upgrade_finishes_at)throw new Error('NO_UPGRADE');if(new Date(row.upgrade_finishes_at).getTime()>Date.now())throw new Error('NOT_READY');const [updated]=await tx`update game.clan_buildings set level=level+1,upgrade_finishes_at=null,updated_at=now() where clan_id=${row.clan_id} and building_code=${code} returning level`;const response={level:updated.level};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

  app.post('/v1/companions/pets/:petId/equip',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const petId=c.req.param('petId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'pet.equip',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [owned]=await tx`select cp.character_id from game.character_pets cp join game.characters ch on ch.id=cp.character_id where ch.player_id=${p} and cp.pet_id=${petId}`;if(!owned)throw new Error('PET_NOT_OWNED');await tx`update game.character_pets set equipped=false where character_id=${owned.character_id}`;await tx`update game.character_pets set equipped=true where character_id=${owned.character_id} and pet_id=${petId}`;const response={equipped:true,petId};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},404);return c.json(out)});

  app.post('/v1/companions/mounts/:mountId/equip',async c=>{let p:string;try{p=await requirePlayerId(c.req.header('authorization'))}catch{return c.json({error:'UNAUTHORIZED'},401)}const mountId=c.req.param('mountId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'mount.equip',key(c));if(r.duplicate)return{duplicate:true,response:r.response};const [owned]=await tx`select cm.character_id from game.character_mounts cm join game.characters ch on ch.id=cm.character_id where ch.player_id=${p} and cm.mount_id=${mountId}`;if(!owned)throw new Error('MOUNT_NOT_OWNED');await tx`update game.character_mounts set equipped=false where character_id=${owned.character_id}`;await tx`update game.character_mounts set equipped=true where character_id=${owned.character_id} and mount_id=${mountId}`;const response={equipped:true,mountId};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},404);return c.json(out)});
}
