import type { Hono } from 'hono';
import type postgres from 'postgres';

type Sql = ReturnType<typeof postgres>;
type RequirePlayerId = (authorization?: string) => Promise<string>;
const n=(v:unknown)=>Number(v??0);
const headersKey=(c:any)=>c.req.header('idempotency-key');
async function auth(c:any,fn:RequirePlayerId){return fn(c.req.header('authorization'));}
async function takeReceipt(tx:any,playerId:string,operation:string,key?:string){
 if(!key||key.length>120)throw new Error('IDEMPOTENCY_KEY_REQUIRED');
 const rows=await tx`insert into game.action_receipts(player_id,operation,idempotency_key) values(${playerId},${operation},${key}) on conflict(player_id,operation,idempotency_key) do nothing returning id`;
 if(rows[0])return{id:rows[0].id,duplicate:false,response:null};
 const [old]=await tx`select response from game.action_receipts where player_id=${playerId} and operation=${operation} and idempotency_key=${key}`;
 return{id:null,duplicate:true,response:old?.response??{}};
}

export function registerSocialRoutes(app:Hono,sql:Sql,requirePlayerId:RequirePlayerId){
 app.get('/v1/clans',async c=>{const q=(c.req.query('q')??'').trim();const rows=q?await sql`select id,name,tag,description,level,experience,(select count(*) from game.clan_members m where m.clan_id=c.id)::int members from game.clans c where lower(name) like ${'%'+q.toLowerCase()+'%'} or lower(tag) like ${'%'+q.toLowerCase()+'%'} order by level desc limit 30`:await sql`select id,name,tag,description,level,experience,(select count(*) from game.clan_members m where m.clan_id=c.id)::int members from game.clans c order by level desc limit 30`;return c.json({clans:rows});});

 app.get('/v1/clan/me',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const [clan]=await sql`select c.*,m.role,m.contribution from game.clan_members m join game.clans c on c.id=m.clan_id where m.player_id=${p}`;if(!clan)return c.json({clan:null});const buildings=await sql`select b.*,d.name_es,d.name_en,d.benefits from game.clan_buildings b join game.clan_building_definitions d on d.code=b.building_code where b.clan_id=${clan.id} order by b.building_code`;const members=await sql`select p.id,p.display_name,ch.name character_name,ch.level,ch.power,m.role,m.contribution from game.clan_members m join game.players p on p.id=m.player_id left join game.characters ch on ch.player_id=p.id where m.clan_id=${clan.id} order by case m.role when 'leader' then 0 when 'officer' then 1 else 2 end,m.contribution desc`;const raids=await sql`select * from game.clan_raids where clan_id=${clan.id} order by starts_at desc limit 10`;return c.json({clan,buildings,members,raids});});

 app.post('/v1/clans',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const name=String(body.name??'').trim().slice(0,40);const tag=String(body.tag??'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5);if(name.length<3||tag.length<2)return c.json({error:'INVALID_CLAN'},400);const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.create',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [membership]=await tx`select clan_id from game.clan_members where player_id=${p}`;if(membership)throw new Error('ALREADY_IN_CLAN');const [clan]=await tx`insert into game.clans(name,tag,description) values(${name},${tag},${String(body.description??'').slice(0,240)}) returning *`;await tx`insert into game.clan_members(clan_id,player_id,role) values(${clan.id},${p},'leader')`;for(const code of ['fortress','bank','forge','library','altar','tower','market','war-room'])await tx`insert into game.clan_buildings(clan_id,building_code) values(${clan.id},${code})`;for(const res of ['gold','ore','wood','arcane_dust'])await tx`insert into game.clan_treasury(clan_id,resource_code,amount) values(${clan.id},${res},0)`;const response={clan};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out,201)});

 app.post('/v1/clans/:clanId/join',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const clanId=c.req.param('clanId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.join',headersKey(c));if(r.duplicate)return{duplicate:true};const [already]=await tx`select clan_id from game.clan_members where player_id=${p}`;if(already)throw new Error('ALREADY_IN_CLAN');const [clan]=await tx`select id from game.clans where id=${clanId}`;if(!clan)throw new Error('CLAN_NOT_FOUND');await tx`insert into game.clan_members(clan_id,player_id) values(${clanId},${p})`;await tx`insert into game.clan_activity(clan_id,actor_player_id,action) values(${clanId},${p},'member_joined')`;await tx`update game.action_receipts set response='{"joined":true}' where id=${r.id}`;return{duplicate:false}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

 app.post('/v1/clan/contribute',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const resource=String(body.resource??'gold');const amount=Math.max(1,Math.min(100000,n(body.amount)));const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.contribute',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [m]=await tx`select m.clan_id,ch.id character_id from game.clan_members m join game.characters ch on ch.player_id=m.player_id where m.player_id=${p}`;if(!m)throw new Error('CLAN_REQUIRED');const [res]=await tx`select amount from game.resources where character_id=${m.character_id} and resource_code=${resource} for update`;if(n(res?.amount)<amount)throw new Error('INSUFFICIENT_RESOURCE');await tx`update game.resources set amount=amount-${amount},updated_at=now() where character_id=${m.character_id} and resource_code=${resource}`;await tx`insert into game.clan_treasury(clan_id,resource_code,amount) values(${m.clan_id},${resource},${amount}) on conflict(clan_id,resource_code) do update set amount=game.clan_treasury.amount+excluded.amount,updated_at=now()`;await tx`update game.clan_members set contribution=contribution+${amount} where clan_id=${m.clan_id} and player_id=${p}`;const response={resource,amount};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

 app.post('/v1/clan/raids/start',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.raid.start',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [m]=await tx`select * from game.clan_members where player_id=${p}`;if(!m||!['leader','officer'].includes(String(m.role)))throw new Error('CLAN_OFFICER_REQUIRED');const [active]=await tx`select id from game.clan_raids where clan_id=${m.clan_id} and status='active' and ends_at>now()`;if(active)throw new Error('RAID_ALREADY_ACTIVE');let boss:any;if(body.bossId)[boss]=await tx`select id,max_hp from game.boss_definitions where id=${String(body.bossId)} and enabled`;else[boss]=await tx`select id,max_hp from game.boss_definitions where enabled order by level limit 1`;if(!boss)throw new Error('BOSS_NOT_FOUND');const hp=n(boss.max_hp)*20;const [raid]=await tx`insert into game.clan_raids(clan_id,boss_id,boss_hp_max,boss_hp_remaining,starts_at,ends_at,rewards) values(${m.clan_id},${boss.id},${hp},${hp},now(),now()+interval '24 hours','{"clan_coins":300,"chest":"clan"}') returning *`;const response={raid};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out,201)});

 app.post('/v1/clan/raids/:raidId/attack',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const raidId=c.req.param('raidId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'clan.raid.attack',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [row]=await tx`select ra.*,m.clan_id membership_clan,ch.power from game.clan_raids ra join game.clan_members m on m.clan_id=ra.clan_id and m.player_id=${p} join game.characters ch on ch.player_id=m.player_id where ra.id=${raidId} for update`;if(!row)throw new Error('RAID_NOT_FOUND');if(row.status!=='active'||new Date(row.ends_at).getTime()<=Date.now())throw new Error('RAID_CLOSED');const [contrib]=await tx`select attempts from game.clan_raid_contributions where raid_id=${raidId} and player_id=${p}`;if(n(contrib?.attempts)>=3)throw new Error('NO_ATTEMPTS');const damage=Math.max(10,Math.round(n(row.power)*(0.65+Math.random()*0.35)));const remaining=Math.max(0,n(row.boss_hp_remaining)-damage);await tx`update game.clan_raids set boss_hp_remaining=${remaining},status=case when ${remaining}=0 then 'defeated' else status end where id=${raidId}`;await tx`insert into game.clan_raid_contributions(raid_id,player_id,damage,attempts) values(${raidId},${p},${damage},1) on conflict(raid_id,player_id) do update set damage=game.clan_raid_contributions.damage+excluded.damage,attempts=game.clan_raid_contributions.attempts+1,updated_at=now()`;const response={damage,remaining,defeated:remaining===0};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

 app.get('/v1/referrals',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const [profile]=await sql`select * from game.referral_profiles where player_id=${p}`;const invited=await sql`select a.attributed_at,p.display_name,ch.level from game.referral_attributions a join game.players p on p.id=a.referred_player_id left join game.characters ch on ch.player_id=p.id where a.referrer_player_id=${p} order by a.attributed_at desc`;const events=await sql`select * from game.earn_events where player_id=${p} and source like 'referral%' order by created_at desc limit 50`;return c.json({profile,invited,events});});

 app.get('/v1/shop',async c=>{const items=await sql`select * from game.shop_items where enabled order by category,price_credits`;const [cfg]=await sql`select value from game.runtime_config where key='premium_credit_packages'`;return c.json({items,creditPackages:cfg?.value??[] ,creditsAreWithdrawable:false});});

 // Compatibility endpoint: old clients are redirected to the complete purchase handler.
 // 307 preserves POST, Authorization and Idempotency-Key so credits can never be debited by the old incomplete path.
 app.post('/v1/shop/:itemId/purchase',c=>c.redirect(`/v1/shop/${c.req.param('itemId')}/purchase-enhanced`,307));

 app.get('/v1/market',async c=>{const rows=await sql`select l.*,d.name_es,d.name_en,d.rarity,d.item_type,p.display_name seller_name from game.market_listings l join game.inventory_items i on i.id=l.inventory_item_id join game.item_definitions d on d.id=i.item_definition_id join game.players p on p.id=l.seller_player_id where l.status='active' order by l.created_at desc limit 100`;return c.json({listings:rows});});

 app.post('/v1/market/list',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const body=await c.req.json().catch(()=>({}));const itemId=String(body.itemId??'');const price=Math.max(1,n(body.price));const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'market.list',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [item]=await tx`select i.id,i.bound,d.tradable from game.inventory_items i join game.characters ch on ch.id=i.character_id join game.item_definitions d on d.id=i.item_definition_id where i.id=${itemId} and ch.player_id=${p} for update`;if(!item||item.bound||!item.tradable)throw new Error('ITEM_NOT_TRADABLE');const [listing]=await tx`insert into game.market_listings(seller_player_id,inventory_item_id,price) values(${p},${itemId},${price}) returning *`;const response={listing};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out,201)});

 app.post('/v1/market/:listingId/buy',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const listingId=c.req.param('listingId');const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'market.buy',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [buyer]=await tx`select id from game.characters where player_id=${p} for update`;const [listing]=await tx`select l.*,i.character_id seller_character_id from game.market_listings l join game.inventory_items i on i.id=l.inventory_item_id where l.id=${listingId} and l.status='active' for update`;if(!buyer||!listing)throw new Error('LISTING_NOT_FOUND');if(String(listing.seller_player_id)===p)throw new Error('SELF_PURCHASE');const [gold]=await tx`select amount from game.resources where character_id=${buyer.id} and resource_code='gold' for update`;if(n(gold?.amount)<n(listing.price))throw new Error('INSUFFICIENT_GOLD');const tax=Math.floor(n(listing.price)*n(listing.tax_rate));const payout=n(listing.price)-tax;await tx`update game.resources set amount=amount-${n(listing.price)},updated_at=now() where character_id=${buyer.id} and resource_code='gold'`;await tx`insert into game.resources(character_id,resource_code,amount) values(${listing.seller_character_id},'gold',${payout}) on conflict(character_id,resource_code) do update set amount=game.resources.amount+excluded.amount,updated_at=now()`;await tx`update game.inventory_items set character_id=${buyer.id} where id=${listing.inventory_item_id}`;await tx`update game.market_listings set status='sold',sold_at=now() where id=${listing.id}`;const response={bought:true,price:n(listing.price),tax,payout};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});

 // Compatibility endpoint: preserve old clients but always execute the complete reward grant path.
 app.post('/v1/battle-pass/:level/:track/claim',c=>c.redirect(`/v1/battle-pass/${c.req.param('level')}/${c.req.param('track')}/claim-enhanced`,307));

 app.get('/v1/arena/me',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const [season]=await sql`select id from game.arena_seasons where now() between starts_at and ends_at limit 1`;if(!season)return c.json({season:null});await sql`insert into game.arena_profiles(season_id,player_id) values(${season.id},${p}) on conflict do nothing`;const [profile]=await sql`select * from game.arena_profiles where season_id=${season.id} and player_id=${p}`;return c.json({season:season.id,profile});});

 app.post('/v1/arena/match',async c=>{let p:string;try{p=await auth(c,requirePlayerId)}catch{return c.json({error:'UNAUTHORIZED'},401)}const out=await sql.begin(async tx=>{const r=await takeReceipt(tx,p,'arena.match',headersKey(c));if(r.duplicate)return{duplicate:true,response:r.response};const [season]=await tx`select id from game.arena_seasons where now() between starts_at and ends_at limit 1`;if(!season)throw new Error('NO_ARENA_SEASON');await tx`insert into game.arena_profiles(season_id,player_id) values(${season.id},${p}) on conflict do nothing`;const [self]=await tx`select ap.*,ch.power from game.arena_profiles ap join game.characters ch on ch.player_id=ap.player_id where ap.season_id=${season.id} and ap.player_id=${p} for update`;const [other]=await tx`select ap.*,ch.power from game.arena_profiles ap join game.characters ch on ch.player_id=ap.player_id where ap.season_id=${season.id} and ap.player_id<>${p} order by abs(ap.rating-${self.rating}) limit 1`;if(!other)throw new Error('NO_OPPONENT');const chance=n(self.power)/(Math.max(1,n(self.power)+n(other.power)));const won=Math.random()<Math.max(.2,Math.min(.8,chance));const delta=won?18:-14;await tx`update game.arena_profiles set rating=greatest(0,rating+${delta}),wins=wins+${won?1:0},losses=losses+${won?0:1},updated_at=now() where season_id=${season.id} and player_id=${p}`;await tx`update game.arena_profiles set rating=greatest(0,rating-${delta}),wins=wins+${won?0:1},losses=losses+${won?1:0},updated_at=now() where season_id=${season.id} and player_id=${other.player_id}`;const [match]=await tx`insert into game.arena_matches(season_id,player_a,player_b,winner,rating_delta_a,rating_delta_b,snapshot) values(${season.id},${p},${other.player_id},${won?p:other.player_id},${delta},${-delta},${tx.json({powerA:self.power,powerB:other.power})}) returning id`;const response={matchId:match.id,won,ratingDelta:delta,opponent:other.player_id};await tx`update game.action_receipts set response=${tx.json(response)} where id=${r.id}`;return{duplicate:false,response}}).catch((e:Error)=>({error:e.message}));if('error'in out)return c.json({error:out.error},409);return c.json(out)});
}
